ballerina-lang/composer

modules/web/js/expression-editor/expression-editor-utils.js
Fix the issue: https://github.com/ballerinalang/composer/issues/1047
=> Fix the issue with expression editor not been editable on the first click

modules/web/js/ballerina/ast/ballerina-ast-root.js
Not setting this was preventing it from being removed.
Fixes #1046
=> Set parent of the dynamic import declaration to current ast root

modules/web/js/ballerina/env/environment.js
This will fix the issue: https://github.com/ballerinalang/composer/issues/1042
=> Removed the "Connection" data type from the types collections.

modules/web/index.html, modules/web/js/menu-bar/help-menu.js, modules/web/js/workspace/workspace.js
This will fix the issue: https://github.com/ballerinalang/composer/issues/1029
=> Added "User Guide" to help menu and point documentation to the ballerina lang.

modules/web/js/ballerina/views/return-types-pane-view.js
issue: https://github.com/ballerinalang/composer/issues/1042
=> Fix Return type pane to get the types from ballerina environment

modules/web/js/ballerina/views/return-types-pane-view.js
Reverts ballerinalang/composer#1077
=> Revert "Fix Return type pane to get the types from ballerina environment"

modules/web/js/ballerina/views/return-types-pane-view.js, modules/web/js/tab/file-tab.js
fix the issue: https://github.com/ballerinalang/composer/issues/1016
=> On file reload scroll of designer set to the top

modules/web/css/ballerina-file-editor.css, modules/web/js/ballerina/views/return-types-pane-view.js
=> fix return type panel ordering,fix for #1053

package.json, webpack.config.js
Added webpack dev server.
Can be run by `npm run dev`
Also skips minifying in development. This makes the build to happen in about 5s with webpack dev server.
=> Add webpack dev server

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/statement-container.js
With this PR, 
Refactors the lifeline height adjustment (Resize Logic) for workers, default workers and the connector declarations
=> Refactoring the lifeline height Resize

modules/web/js/ballerina/views/ballerina-file-editor.js
Fix the issue: https://github.com/ballerinalang/composer/issues/1104
=> Fix the issue with package auto complete list to clear selection after adding

modules/web/js/ballerina/views/message.js, modules/web/js/ballerina/views/worker-invoke-view.js
=> Fixing worker invoke arrow reposition issue

modules/web/resources/samples/routingServices.bal
=> Fixing routinServices sample s/jsonUtils/jsons

modules/web/js/ballerina/views/ballerina-file-editor.js, modules/web/js/ballerina/views/type-mapper-definition-view.js, modules/web/js/type-mapper/type-mapper-renderer.js
=> jsPlumb is not exported as default from 'jsplumb'

modules/web/js/ballerina/views/resource-definition-view.js
When we delete a worker when there are added connectors, this won't re position the connectors accordingly
=> Fixing worker delete issue

modules/services/workspace-service/dependency-reduced-pom.xml, modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/function-definition-view.js
This fixes the issue of deleting workers from the function definitions and the connector actions
=> Fixing worker delete issue for function def and action

modules/web/js/ballerina/views/service-definition-view.js
Fixing resource definition initial width calculation
=> Fixing resource definition initial width calculation

modules/web/js/debugger/debug-manager.js
fix for https://github.com/ballerinalang/composer/issues/1113
=> fix error Could not preserve debug points error in other bal files

modules/web/js/ballerina/views/function-definition-view.js
Fixing function definition width expand
=> Fixing function definition width expand

modules/web/index.js, modules/web/js/ballerina/views/ballerina-file-editor.js, modules/web/js/debugger/channel.js, modules/web/js/debugger/debug-manager.js, modules/web/js/debugger/frames.js, modules/web/js/debugger/module.js, modules/web/js/debugger/tools.js
fixes https://github.com/ballerinalang/composer/issues/1007
=> refactor debugger shortcuts

modules/web/js/ballerina/views/block-statement-view.js, modules/web/js/ballerina/views/bounding-box.js, modules/web/js/ballerina/views/compound-statement-view.js, modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/life-line.js, modules/web/js/ballerina/views/reply-statement-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/simple-statement-view.js, modules/web/js/ballerina/views/statement-container.js, modules/web/js/ballerina/views/worker-declaration-view.js, modules/web/js/ballerina/views/worker-invocation-view.js, modules/web/js/ballerina/views/worker-reply-statement-view.js
With this PR, we introduce the enhancement for horizontal expand of the components
=> Revamp the statement horizontal expand

modules/web/js/ballerina/views/action-invocation-statement-view.js, modules/web/js/ballerina/views/block-statement-view.js, modules/web/js/ballerina/views/statement-container.js
=> Fixing action invocation drop issue for inner drop zones

modules/web/js/ballerina/ast/struct-definition.js
related to https://github.com/ballerinalang/composer/issues/1188
=> add validation to struct variable definition

modules/web/css/styles.css
related to https://github.com/ballerinalang/composer/issues/1182
=> change file dialog hover

modules/web/js/ballerina/ast/resource-definition.js, modules/web/js/ballerina/visitors/source-gen/resource-definition-visitor.js
Fixes : https://github.com/ballerinalang/composer/issues/856
=> Renamed method annotation to Http:Method

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js
=> Fixing Connector declaration Reposition Issue

README.md
We need nodejs, only npm is not enough. Nodejs comes with npm.
=> Add nodejs to prerequisites

modules/web/js/ballerina/views/block-statement-view.js, modules/web/js/ballerina/views/compound-statement-view.js, modules/web/js/ballerina/views/return-type-view.js
Fix the issue: https://github.com/ballerinalang/composer/issues/1197
=> Added delete event to the return type in the return type edit view of task bar controls

modules/web/js/ballerina/views/action-invocation-statement-view.js
=> Fix action Invocation Delete Issue

modules/web/js/ballerina/views/ballerina-statement-view.js
fix for https://github.com/ballerinalang/composer/issues/1202
=> fix debug point indicator mis-alignments in design view

modules/web/js/ballerina/views/variable-definitions-pane-view.js
Fixes : https://github.com/ballerinalang/composer/issues/1206
=> Removed error alert when adding a valid identifier for a variable.

modules/web/js/ballerina/views/function-arguments-view.js
Fixes : https://github.com/ballerinalang/composer/issues/1208
=> Showing the error alert when an argument with an invalid identifer is being added.

pom.xml
Reverts ballerinalang/composer#1215
=> Revert "Change ballerina-parent pom version"

pom.xml
Reverts ballerinalang/composer#1217
=> Revert "Revert "Change ballerina-parent pom version""

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js
Fixing lifeline unnecessary minify issue
=> Fixing lifeline unnecessary minify issue

modules/web/js/ballerina/views/statement-container.js
=> When a statement is added select the relevant inner drop zone if not selected

modules/web/js/ballerina/ast/connector-action.js, modules/web/js/ballerina/ast/connector-definition.js, modules/web/js/ballerina/ast/function-definition.js, modules/web/js/ballerina/ast/resource-definition.js, modules/web/js/ballerina/ast/service-definition.js, modules/web/js/ballerina/env/package.js, modules/web/js/ballerina/views/action-invocation-statement-view.js
This fixes the issue #1224 and revamp the connector action invocation statement
=> Fixing the connector action invocation issue

README.md, modules/web/.eslintignore, modules/web/.eslintrc.js, modules/web/js/ballerina/tool-palette/tool-palette.js, modules/web/js/ballerina/views/annotation-view.js, modules/web/js/debugger/module.js, modules/web/js/dialog/module.js, modules/web/js/dialog/open-file-dialog.js, modules/web/js/main.js, modules/web/js/tests/js/spec/BallerinaTest.js, modules/web/js/tests/js/spec/setup.js, modules/web/js/type-mapper/type-mapper-renderer.js, modules/web/js/welcome-page/module.js, modules/web/js/workspace/browser-storage.js, modules/web/package.json
Currently rules for many common mistakes are turned off. Need to fix and turn them on.
To run,
`npm run lint`
To automatically fix some problems,
`npm run lint -- --fix`
=> Add eslint to lint JS code

modules/web/css/ballerina-file-editor.css, modules/web/js/ballerina/views/ballerina-file-editor.js
fixes https://github.com/ballerinalang/composer/issues/666
=> Fix import typeahead issue firefox

modules/web/js/ballerina/views/worker-invocation-view.js, modules/web/js/ballerina/views/worker-reply-statement-view.js
With this PR fixes the issue #1260
=> Fixing the worker invoke and reply arrow positioning

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/connector-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/service-definition-view.js
=> Fixing the resource resizing on connector adding

modules/web/js/ballerina/views/life-line.js
Steps to Reproduce
Add a connector
Add a connector invocation
Now delete the connector and an error would be thrown on the console.
With this fixes the aforementioned issue
=> Fixing issue when deleting connector declaration with action invoked

modules/web/css/layout.css, modules/web/js/debugger/module.js, modules/web/js/launcher/launcher.js, modules/web/js/workspace/explorer.js
fixes https://github.com/ballerinalang/composer/issues/1048
=> fix sidebar resize on firefox

modules/web/js/ballerina/ast/callable-definition.js, modules/web/js/ballerina/views/ballerina-view.js, modules/web/js/ballerina/views/canvas.js, modules/web/js/ballerina/views/connector-declaration-view.js
Any place where arguments passed up the super call, editing of arguments have to be before the super call.
=> Minor fixes to super calls

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/connector-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/service-definition-view.js
=> migrating PR#1264 to es-6

modules/web/js/ballerina/views/life-line.js
=> migrating PR#1266 to es6

modules/web/js/ballerina/ast/resource-definition.js, modules/web/js/ballerina/ast/resource-parameter.js, modules/web/js/ballerina/ast/service-definition.js, modules/web/js/ballerina/visitors/source-gen/resource-definition-visitor.js, modules/web/js/ballerina/visitors/source-gen/service-definition-visitor.js
=> Migrating PR#1276 to es-6

modules/web/js/ballerina/views/annotation-view.js
With this PR we fixes the issue of not be able to add or remove the annotations.
=> Fix annotation add and delete issue

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/connector-definition-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/service-definition-view.js
=> Fixing Issue #230

modules/web/js/ballerina/utils/ace-formatter.js, modules/web/js/ballerina/utils/ace-mode.js
* Fix adding a space between a tab and identifier
* Fix indentation not adding for nested empty block '}'s
=> Fix code formatting issues.

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/connector-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/service-definition-view.js, modules/web/js/ballerina/views/variable-definition-view.js, modules/web/js/ballerina/views/variable-definitions-pane-view.js
=> Fix Issue #1019

modules/web/js/launcher/console.js
This PR fixes the issue of html tags not displaying the xml special characters.
=> Fix Issue No:880

modules/web/js/ballerina/ast/statements/statement.js
This PR fixes the issue occurred when adding an action invocation inside a if else statement.
=> Fix issue of adding action invocation inside If-else

modules/web/js/ballerina/ast/statements/statement.js, modules/web/js/ballerina/env/package.js, modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/function-arguments-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/resource-parameters-pane-view.js, modules/web/js/ballerina/views/return-types-pane-view.js
With this fix,
The types in the drop down lists for arguments, return types, parameters, etc, will be dynamically populated with the types defined in the current package.
=> Fix Issue No: 477

modules/web/js/ballerina/views/while-statement-view.js
With this PR we fixes the Issue #1304
=> Fix Issue 1304

modules/web/css/styles.css, modules/web/js/ballerina/views/assignment-view.js, modules/web/js/ballerina/views/ballerina-file-editor.js, modules/web/js/ballerina/views/ballerina-statement-view.js, modules/web/js/ballerina/views/variable-definition-statement-view.js, modules/web/js/expression-editor/expression-editor-utils.js
With this initial commit, validate the following,
Assignment statement
Variable Definition
=> Validate node type on edit statement

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LaunchServerHandler.java
=> debugger - ensure running program terminate when websocket connection drops. 

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/PackagesApiServiceImpl.java
This reverts commit ccfa35de04653c9c7623f8bad3a4da1bd87d2562.
=> Revert "Fully resolve symbol scope & native packages"

modules/web/js/ballerina/views/connector-action-view.js, modules/web/js/ballerina/views/connector-definition-view.js, modules/web/js/ballerina/views/function-definition-view.js, modules/web/js/ballerina/views/life-line.js, modules/web/js/ballerina/views/resource-definition-view.js, modules/web/js/ballerina/views/service-definition-view.js
With this PR, fixes the issue #1367
=> Fix Issue No:1367

modules/web/js/ballerina/item-provider/tool-palette-item-provider.js
https://github.com/ballerinalang/composer/issues/1373
=> Support array return types for Function invocation statements

modules/distribution/index.js, modules/distribution/src/app.js, modules/distribution/src/workspace.js, modules/web/electron-index.js, modules/web/js/main.js, modules/web/js/menu-bar/menu-bar.js, modules/web/js/workspace/service-client.js, modules/web/js/workspace/workspace.js
Includes a few fixes for electron build and implement isElectronMode flag for app
=> Enable native wizards for file/folder open & save

modules/web/js/ballerina/ast/statements/block-statement.js, modules/web/js/ballerina/ast/type-mapper-definition.js, modules/web/js/ballerina/visitors/source-gen/type-mapper-variable-definition-statement-visitor.js, modules/web/js/tests/resources/BalList.json, modules/web/js/tests/resources/typemappers/complex-inner-mapping.bal, modules/web/js/tests/resources/typemappers/complex-mapping.bal, modules/web/js/tests/resources/typemappers/simple-mapping.bal
Type mapper test cases added
Type mapper line order changing issue fixed
=> Type mapper test cases added & order changing issue fixed

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/ast/expressions/function-invocation-expression.js, modules/web/js/ballerina/env/package-scoped-environment.js, modules/web/js/ballerina/views/type-mapper-function-assignment-view.js, modules/web/js/type-mapper/type-mapper-renderer.js
https:/github.com/ballerinalang/composer/issues/1397
=> support package knowledge for function nodes in type mapper

modules/web/js/ballerina/components/lifeline.jsx
Adding init impl of the lifeline passive react comp.
=> adding lifeline component.

modules/web/js/ballerina/components/canvas-decorator.jsx, modules/web/js/ballerina/components/diagram.jsx, modules/web/js/ballerina/components/panel-decorator.jsx, modules/web/js/ballerina/components/resource-definition.jsx
Adding a panel and sample resource.
=> React development panel

modules/web/js/ballerina/visitors/dimension-calculator/function-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/position-calc/worker-declarion-position-calc.js
adding worker width to panel width.
=> Correcting panel width.

modules/web/js/ballerina/components/canvas-decorator.jsx, modules/web/js/ballerina/components/diagram.jsx, modules/web/js/ballerina/components/package-definition.css, modules/web/js/ballerina/components/package-definition.jsx, modules/web/js/ballerina/components/text-input.css, modules/web/js/ballerina/components/text-input.jsx, modules/web/js/ballerina/configs/app-context.js, modules/web/js/ballerina/configs/designer-defaults.js
Add utility function renderTextInput to render a text input over svg canvas
=> Add initial implementation for package definition component

modules/web/css/diagram/diagram.css, modules/web/js/ballerina/components/struct-definition.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/visitors/dimension-calculator/struct-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/position-calc/struct-definition-position-calc.js, modules/web/js/ballerina/visitors/position-calc/utils.js
=> Struct definition

modules/web/js/ballerina/components/annotation-attribute-decorator.jsx, modules/web/js/ballerina/components/canvas-decorator.jsx, modules/web/js/ballerina/components/diagram.jsx, modules/web/js/ballerina/components/package-definition.jsx, modules/web/js/ballerina/components/renderer.jsx, modules/web/js/ballerina/views/ballerina-file-editor.js
The html rendering works with multiple tabs now.
=> Add renderer to render html over svg

modules/web/js/ballerina/components/diagram.jsx, modules/web/js/ballerina/components/editable-text.jsx, modules/web/js/ballerina/components/panel-decorator.jsx, modules/web/js/ballerina/views/ballerina-file-editor.js
=> Make panel titles editable with EditableText

modules/web/js/ballerina/components/import-declaration-expanded.jsx, modules/web/js/ballerina/components/import-declaration.jsx, modules/web/js/ballerina/visitors/dimension-calculator/package-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/sizing-utils.js
Import number background is adjusted correctly when number of imports grows
=> Import badge lengths are set correctly

modules/web/js/ballerina/ast/annotation-definition.js, modules/web/js/ballerina/ast/parameter-definition.js, modules/web/js/ballerina/components/annotation-definition-attachment.jsx, modules/web/js/ballerina/components/annotation-definition.jsx, modules/web/js/ballerina/components/argument-parameter-definition-holder.jsx, modules/web/js/ballerina/components/connector-action-definition.jsx, modules/web/js/ballerina/components/connector-definition.jsx, modules/web/js/ballerina/components/function-definition.jsx, modules/web/js/ballerina/components/panel-decorator.jsx, modules/web/js/ballerina/components/resource-definition.jsx, modules/web/js/ballerina/components/return-parameter-definition-holder.jsx, modules/web/js/ballerina/components/utils/tag-component.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/env/environment.js, modules/web/js/ballerina/visitors/dimension-calculator/annotation-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/connector-action-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/connector-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/function-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/resource-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/position-calc/annotation-definition-position-calc.js, modules/web/js/ballerina/visitors/position-calc/connector-action-position-calc.js, modules/web/js/ballerina/visitors/position-calc/connector-definition-position-calc.js, modules/web/js/ballerina/visitors/position-calc/function-definition-position-calc.js, modules/web/js/ballerina/visitors/position-calc/resource-position-calc.js
Fix positioning issues of panel header
Added Functionality to add attachments to annotation definition
Fix the issue with parameter definition annotations
Fix some code formatting issues
=> Implemented Annotation attachment adding functionality

modules/web/js/ballerina/ast/ballerina-ast-factory.js, modules/web/js/ballerina/ast/statements/if-else-statement.js, modules/web/js/ballerina/components/throw-statement.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/visitors/dimension-calculator/while-statement-dimension-calculator-visitor.js
- Add Default else statement
- Increase while statement height when empty,
- Increase block statement width
- Add expression editor to throw statement
=> Improvements and bug fixes

modules/web/js/ballerina/ast/ballerina-ast-factory.js, modules/web/js/ballerina/ast/node.js, modules/web/js/ballerina/components/panel-decorator.css
Also Fix panel dropzone feedbacks
=> Get whitespace descriptors to javascript AST &  Fix panel dropzone feedbacks

modules/web/js/ballerina/components/annotation-attribute-decorator.jsx, modules/web/js/ballerina/components/annotation-attribute-definition.jsx, modules/web/js/ballerina/components/annotation-definition.css, modules/web/js/ballerina/components/editable-text.jsx, modules/web/js/ballerina/components/utils/tag-component.css, modules/web/js/ballerina/components/utils/tag-component.jsx
- fixed Argument Parameter adding
- fixed Return Parameter adding  
- fixed Annotation Attachment adding
=> Fix the issue with tag controller.

modules/web/js/ballerina/components/editable-text.jsx
=> Stop rendering of text box making the text appear to jump

modules/web/js/ballerina/ast/expressions/reference-type-init-expression.js
Fixes : https://github.com/ballerinalang/composer/issues/1668
=> Fixed generateExpression for reference-type-init-expression

modules/web/js/ballerina/views/ballerina-file-editor.js
fix error in design view when bal has parse errors : https://github.com/ballerinalang/composer/issues/1692
=> Fix for https://github.com/ballerinalang/composer/issues/1692

modules/web/js/ballerina/ast/statements/if-else-statement.js
=> Avoid adding empty else block when no else block present

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/ast/ballerina-ast-factory.js, modules/web/js/ballerina/ast/default-ballerina-ast-factory.js, modules/web/js/ballerina/ast/statements/abort-statement.js, modules/web/js/ballerina/ast/statements/aborted-statement.js, modules/web/js/ballerina/ast/statements/transaction-statement.js, modules/web/js/ballerina/ast/statements/transactionaborted-statement.js, modules/web/js/ballerina/components/abort-statement.jsx, modules/web/js/ballerina/components/aborted-statement.jsx, modules/web/js/ballerina/components/block-statement-decorator.jsx, modules/web/js/ballerina/components/transaction-aborted-statement.jsx, modules/web/js/ballerina/components/transaction-statement.jsx, modules/web/js/ballerina/item-provider/initial-definitions.js, modules/web/js/ballerina/utils/ace-mode.js, modules/web/js/ballerina/visitors/dimension-calculator/abort-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/aborted-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/transaction-aborted-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/transaction-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/position-calc/abort-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/aborted-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/transaction-aborted-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/transaction-statement-position-calc-visitor.js, modules/web/js/ballerina/visitors/source-gen/abort-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/aborted-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/statement-visitor-factory.js, modules/web/js/ballerina/visitors/source-gen/transaction-aborted-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/transaction-statement-visitor.js, modules/web/js/ballerina/visitors/statement-visitor.js
- Added Transaction Aborted Statement
- Added Transaction Statement
- Added Aborted Statement
- Added Abort Statement
- Fix some formatting issues.
=> Added Transaction-Aborted Statement

modules/web/js/ballerina/visitors/source-gen/comment-statement-visitor.js
Fix the issue https://github.com/ballerinalang/composer/issues/1542
=> Fix the issue where comment adding a semicolon at the end

modules/web/js/ballerina/components/import-declaration-expanded.jsx, modules/web/js/ballerina/components/package-definition.jsx, modules/web/js/ballerina/components/suggestions-text.jsx, modules/web/js/ballerina/views/ballerina-file-editor.js
* Already imported packages are not suggested
* Typed query is shown hightlighted in the suggestions box
Fixes #1682
=> UI improvements to add import component

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/ast/ballerina-ast-factory.js, modules/web/js/ballerina/ast/else-if-condition.js, modules/web/js/ballerina/ast/expressions/action-invocation-expression.js, modules/web/js/ballerina/ast/expressions/back-tick-expression.js, modules/web/js/ballerina/ast/expressions/type-conversion-expression.js, modules/web/js/ballerina/ast/expressions/unary-expression.js, modules/web/js/ballerina/ast/statements/if-else-statement.js, modules/web/js/ballerina/visitors/expression-visitor.js, modules/web/js/ballerina/visitors/source-gen/type-conversion-expression-visitor.js, modules/web/js/tests/js/spec/BallerinaTest.js
This PR includes the following
- Fixing the expression test cases
- Adding the support for type conversion
- Adding the else-if expression generation
=> Fixing test cases

modules/web/js/ballerina/components/annotation-attribute-definition.jsx, modules/web/js/ballerina/components/parameter-definition.jsx, modules/web/js/ballerina/components/utils/tag-component.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/visitors/dimension-calculator/function-definition-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/sizing-utils.js
-Fix the positioning of title and truncating issues of the function definition.
-Fix the annotation definition positioning issue.
=> Fix the positioning issues of function definition and annotation definition

modules/web/js/ballerina/ast/ballerina-ast-factory.js, modules/web/js/ballerina/ast/statements/if-else-statement.js, modules/web/js/ballerina/components/block-statement-decorator.jsx, modules/web/js/ballerina/components/compound-statement-decorator.jsx, modules/web/js/ballerina/components/else-if-statement.jsx, modules/web/js/ballerina/components/else-statement.jsx, modules/web/js/ballerina/components/if-statement.css, modules/web/js/ballerina/components/if-statement.jsx
=> Add 'else' and 'else-if' statements separately to 'if' statements

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/web/js/ballerina/ast/statements/catch-statement.js, modules/web/js/ballerina/components/catch-statement.jsx, modules/web/js/ballerina/visitors/dimension-calculator/catch-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/source-gen/catch-statement-visitor.js, modules/web/js/tests/resources/core-tests/ballerina-native/src/main/ballerina/ballerina/lang/errors/duplicate-var-try-catch.bal, modules/web/js/tests/resources/core-tests/ballerina-native/src/main/ballerina/ballerina/lang/errors/error_return.bal
Fixes the issue #1740 and adding the respective test cases
=> Fix Issue No 1740

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangExpressionModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java
Reverts ballerinalang/composer#1768
This is to fix compilation issues with ballerina-core
=> Revert "fix compilation errors due to arraylength expression"

modules/web/js/ballerina/components/annotation-container.jsx, modules/web/js/ballerina/components/panel-decorator.jsx, modules/web/js/ballerina/components/parameter-definition.jsx, modules/web/js/ballerina/components/utils/tag-component.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/visitors/position-calc/utils.js, modules/web/js/ballerina/visitors/sizing-utils.js
Reverts ballerinalang/composer#1808
Reverting this to move the height adjustments to dimension calculators.
=> Revert "Fixing git issue #1801 and #1806"

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/ast/statements/fork-join-statement.js, modules/web/js/ballerina/ast/statements/timeout-statement.js, modules/web/js/ballerina/components/block-statement-decorator.jsx, modules/web/js/ballerina/components/join-statement.css, modules/web/js/ballerina/components/join-statement.jsx, modules/web/js/ballerina/components/timeout-statement.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/visitors/dimension-calculator/fork-join-statement-dimension-calculator.js, modules/web/js/ballerina/visitors/dimension-calculator/join-statement-dimenstion-calculator.js, modules/web/js/ballerina/visitors/dimension-calculator/timeout-statement-dimenstion-calculator.js, modules/web/js/ballerina/visitors/position-calc/timeout-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/worker-declaration-position-calc.js, modules/web/js/ballerina/visitors/sizing-utils.js, modules/web/js/ballerina/visitors/source-gen/timeout-statement-visitor.js, modules/web/js/ballerina/visitors/statement-visitor.js
=>  Timeout ui improvements.

modules/web/js/ballerina/components/annotation-definition.jsx, modules/web/js/ballerina/components/argument-parameter-definition-holder.jsx, modules/web/js/ballerina/components/return-parameter-definition-holder.jsx, modules/web/js/ballerina/components/utils/tag-component.jsx, modules/web/js/ballerina/visitors/position-calc/utils.js, modules/web/js/ballerina/visitors/sizing-utils.js
Fix the issue: https://github.com/ballerinalang/composer/issues/1802
=> Change the text in tag controller to match the input type

modules/web/js/ballerina/components/panel-decorator.jsx
(In addition to pressing enter)
=> When renaming panel titles are set on bluring of the text input.

modules/web/config.js, modules/web/webpack.config.js
- one Image is not loading on welcome page
- cannot run js test due to a webpack issue
=> Fix the issue where js tests are not running

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/web/js/ballerina/ast/expressions/type-cast-expression.js
=> Fix Issue No 1873

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/ast/statements/fork-join-statement.js, modules/web/js/ballerina/ast/statements/timeout-statement.js, modules/web/js/ballerina/components/block-statement-decorator.jsx, modules/web/js/ballerina/components/join-statement.css, modules/web/js/ballerina/components/join-statement.jsx, modules/web/js/ballerina/components/timeout-statement.jsx, modules/web/js/ballerina/configs/designer-defaults.js, modules/web/js/ballerina/visitors/dimension-calculator/fork-join-statement-dimension-calculator.js, modules/web/js/ballerina/visitors/dimension-calculator/join-statement-dimenstion-calculator.js, modules/web/js/ballerina/visitors/dimension-calculator/timeout-statement-dimenstion-calculator.js, modules/web/js/ballerina/visitors/position-calc/timeout-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/worker-declaration-position-calc.js, modules/web/js/ballerina/visitors/sizing-utils.js, modules/web/js/ballerina/visitors/source-gen/timeout-statement-visitor.js, modules/web/js/ballerina/visitors/statement-visitor.js
Reverts ballerinalang/composer#1810
This will revert the master to bvm branch starting point
=> Revert " Timeout ui improvements."

modules/web/js/ballerina/ast/annotations/annotation-entry.js
Fixes : https://github.com/ballerinalang/composer/issues/1910 and https://github.com/ballerinalang/composer/issues/1911
=> Fixed overlapping of annotations.

modules/web/js/ballerina/components/statement-container.jsx, modules/web/js/ballerina/components/worker-invocation-statement.jsx, modules/web/webpack.config.js
=> Fix Issue No 1958

modules/web/js/ballerina/env/connector-action.js, modules/web/js/ballerina/env/connector.js, modules/web/js/ballerina/env/function.js, modules/web/js/ballerina/env/package.js, modules/web/js/ballerina/item-provider/tool-palette-item-provider.js, modules/web/js/ballerina/tool-palette/tool-palette-view.jsx, modules/web/js/ballerina/visitors/symbol-table/ballerina-ast-root-visitor.js
Related issue : https://github.com/ballerinalang/composer/issues/1907
=> Tool Palette remove events and fix update issues

modules/web/js/ballerina/ast/connector-declaration.js, modules/web/js/ballerina/ast/default-ballerina-ast-factory.js, modules/web/js/ballerina/ast/expressions/connector-init-expression.js, modules/web/js/ballerina/components/connector-declaraion.jsx, modules/web/js/ballerina/item-provider/tool-palette-item-provider.js, modules/web/js/ballerina/visitors/source-gen/connector-declaration-visitor.js, modules/web/webpack.config.js
=> Fix Issue No 1920

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LaunchManager.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LauncherConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/TerminatorFactory.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/TerminatorUnix.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/TerminatorWindows.java
- adds doc comments to Terminator classes
- Handles possible null pointer issues.
=> add doc comments to terminator classes

modules/web/js/ballerina/visitors/find-breakpoint-lines-visitor.js, modules/web/js/ballerina/visitors/find-breakpoint-nodes-visitor.js, modules/web/js/ballerina/visitors/find-debug-hit-visitor.js, modules/web/js/debugger/module.js, modules/web/js/launcher/launcher.js
- adds jsdoc comments to debugger visitors
=> add jsdoc comments in debugger visitors

modules/web/js/ballerina/ast/ballerina-ast-root.js, modules/web/js/ballerina/ast/connector-declaration.js, modules/web/js/ballerina/ast/default-ballerina-ast-factory.js, modules/web/js/ballerina/ast/statements/assignment-statement.js, modules/web/js/ballerina/item-provider/tool-palette-item-provider.js
fix issue : https://github.com/ballerinalang/composer/issues/1908
=> fix auto import issue when adding functions, connector dec and action invocations

modules/web/js/ballerina/ast/statements/while-statement.js, modules/web/js/ballerina/ast/statements/worker-invocation-statement.js, modules/web/js/ballerina/ast/statements/worker-reply-statement.js, modules/web/js/ballerina/visitors/source-gen/enable-default-ws-visitor.js, modules/web/js/ballerina/visitors/source-gen/while-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/worker-invocation-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/worker-reply-statement-visitor.js
Can be merged once https://github.com/ballerinalang/ballerina/pull/2659 is merged to core.
=> Whitespace fixes

modules/web/js/ballerina/ast/node.js, modules/web/js/ballerina/views/ballerina-file-editor.js, modules/web/js/ballerina/visitors/find-debug-hit-visitor.js
fix for https://github.com/ballerinalang/composer/issues/1934 and https://github.com/ballerinalang/composer/issues/1913
=> fix file dirty when debugging

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/Workspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/cloud/CloudWorkspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/local/LocalFSWorkspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/WorkspaceService.java, modules/web/js/ballerina/components/service-definition.jsx, modules/web/js/dialog/swagger-import-dialog.js, modules/web/js/file-browser/file-browser.js, modules/web/js/menu-bar/file-menu.js, modules/web/js/swagger-parser/swagger-parser.js, modules/web/js/tab/file-tab.js, modules/web/js/workspace/manager.js
Fixes: https://github.com/ballerinalang/composer/issues/2029
=> Added feature to create a service using a swagger definition file. Fixed minor bugs and updated service.

modules/web/js/ballerina/components/transform-statement-decorator.jsx
Fix for https://github.com/ballerinalang/composer/issues/2042
=> support arguments for transform input and output

modules/web/js/debugger/debugger.css, modules/web/js/launcher/console.js
fixes https://github.com/ballerinalang/composer/issues/1914
=> preserve stack trace formatting in laucher console

modules/web/js/ballerina/ast/node.js, modules/web/js/ballerina/visitors/source-gen/import-declaration-visitor.js
This fixes the whitespace issue when adding new imports to an existing file.
=> Fix issues with import-declr WS

modules/web/js/dialog/open-file-dialog.js
Fix the issue: https://github.com/ballerinalang/composer/issues/454
=> Fix the Issue 454

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangExpressionModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java
This PR is depend on https://github.com/ballerinalang/ballerina/pull/2711
=> Add continue stmt support.

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/TerminatorUnix.java
fixes https://github.com/ballerinalang/composer/issues/1666
=> terminate with child processes in stop program

modules/web/js/ballerina/components/variable-definition-statement.jsx
=> Fix Issue No 2096

modules/web/js/ballerina/components/struct-definition.jsx
fixes https://github.com/ballerinalang/composer/issues/1942
=> add quotes to default value if type is string

modules/web/js/ballerina/visitors/symbol-table/ballerina-ast-root-visitor.js
=> Fix Issue No 2097

modules/web/js/ballerina/components/lifeline.jsx, modules/web/js/ballerina/components/return-parameter-definition-holder.jsx
=> Fix Issues 2021, 1938

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/CompletionItemAccumulator.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/dto/CompletionItem.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/DefaultResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ItemResolverConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/PackageNameContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/StatementContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/VariableDefinitionStatementContextResolver.java, modules/web/css/styles.css, modules/web/js/ballerina/utils/source-view-completer-factory.js
Adding the sort order of the Items
Adding the completion Item type
Increase auto complete box's size 
= Important =
For the last improvement we override the css of the ace editor
=> Improvements for the autocompletions

modules/web/js/ballerina/components/annotation-attribute.jsx, modules/web/js/ballerina/components/annotation-container.jsx, modules/web/js/ballerina/components/annotation.jsx, modules/web/js/ballerina/components/utils/autosuggest-html.jsx
Fixes for :
https://github.com/ballerinalang/composer/issues/1992 - Allows multiple Connection Properties.
https://github.com/ballerinalang/composer/issues/2098
https://github.com/ballerinalang/composer/issues/2100 - Should be able to delete annotations from the UI
https://github.com/ballerinalang/composer/issues/2129
https://github.com/ballerinalang/composer/issues/2050
=> Fixes related to Annotations.

modules/web/js/launcher/launch-manager.js
related to https://github.com/ballerinalang/composer/issues/1004
=> temporary fix to handle too many console printlns

modules/web/js/ballerina/tool-palette/tool-palette-view.jsx, modules/web/js/ballerina/tool-palette/tool-palette.css
Fixing issue [https://github.com/ballerinalang/composer/issues/2093]
=> [#2093] Changed to tool palette view more 

modules/web/js/welcome-page/first-launch-welcome.js, modules/web/js/welcome-page/welcome.jsx
Fixing issue [https://github.com/ballerinalang/composer/issues/2093]
=> [#2155] fixing git issue

modules/web/js/ballerina/components/package-definition.jsx
=> Sort imports in the imports drop-down

modules/web/js/ballerina/utils/ace-mode.js
https://github.com/ballerinalang/composer/issues/2254
=> add keyword any and remove long and double

modules/web/js/ballerina/ast/node.js, modules/web/js/ballerina/components/struct-definition.jsx
https://github.com/ballerinalang/composer/issues/2283
=> Allowing struct type fields to be imported and to show the imported types in the design view

modules/web/js/ballerina/components/struct-definition.jsx
Fixed : https://github.com/ballerinalang/composer/issues/2329
=> Handling the default values of the struct string fields

modules/web/js/ballerina/components/struct-definition.jsx
Fixed issue : https://github.com/ballerinalang/composer/issues/2337
=> Allowing default values in structs to be removed once added

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/CallableUnitBodyContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/suggetions/AutoCompleteSuggesterImpl.java
This includes the fix for initial content assist for the conditional statements such as if, while, else if
=> Lang server fixes

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/filters/PackageActionAndFunctionFilter.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/AbstractItemResolver.java
With this PR, we make the function/ action template which is to be inserted, adhere to the actual function/action signature
=> Adding the function template adhering to the signature

modules/web/js/ballerina/components/struct-definition.jsx
Fixed issue: https://github.com/ballerinalang/composer/pull/2338
=> Updating the default value of the variable definition given in structs

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFragmentParser.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFragmentParserConstants.java, modules/web/js/ballerina/components/argument-parameter-definition-holder.jsx, modules/web/js/ballerina/components/return-parameter-definition-holder.jsx, modules/web/js/ballerina/utils/fragment-utils.js
This will fix the issue: https://github.com/ballerinalang/composer/issues/2328
=> Added annotation support for parameters

modules/web/js/ballerina/components/package-definition.jsx
=> Add tool tip to package def image

modules/web/css/ballerina-file-editor.css, modules/web/js/ballerina/ast/service-definition.js, modules/web/js/ballerina/ast/statements/assignment-statement.js, modules/web/js/ballerina/ast/statements/variable-definition-statement.js, modules/web/js/ballerina/components/action-box.jsx, modules/web/js/ballerina/components/breakpoint.jsx, modules/web/js/ballerina/components/global-definitions.jsx, modules/web/js/ballerina/components/import-declaration.jsx, modules/web/js/ballerina/components/package-definition.jsx, modules/web/js/ballerina/components/panel-decorator-button.jsx, modules/web/js/ballerina/components/panel-decorator.jsx, modules/web/js/ballerina/components/popout-button.jsx, modules/web/js/ballerina/components/service-definition.jsx, modules/web/js/ballerina/components/struct-definition.jsx, modules/web/js/ballerina/item-provider/initial-definitions.js, modules/web/js/ballerina/tool-palette/tool-palette-view.jsx, modules/web/js/ballerina/tool-palette/tool-palette.css, modules/web/js/ballerina/tool-palette/tool-view.jsx
Fixed issue : https://github.com/ballerinalang/composer/issues/2357
=> Validating the default values provided for a variable definition and Improving the tool palette, debug menu and canvas

modules/web/js/ballerina/components/transform-endpoints-dropdown.jsx, modules/web/js/ballerina/components/transform-expanded.jsx
* Inner structs are not added to dropdown
* TypeName is displayed for structs
=> Fixes 2391

modules/web/js/ballerina/components/break-statement.jsx
Fixed issue : https://github.com/ballerinalang/composer/issues/2400
=> Fixing the issue in the break statement in the design view

modules/web/js/ballerina/components/transform-endpoints-dropdown.jsx, modules/web/js/ballerina/components/transform-expanded.jsx
* AddSource and AddTarget inputs are cleared when added
* Can be added by pressing enter
=> Transform expanded UI improvements

modules/web/js/ballerina/components/abort-statement.jsx, modules/web/js/ballerina/visitors/source-gen/abort-statement-visitor.js
This fixes the issue: https://github.com/ballerinalang/composer/issues/2311
=> Fixing the inconsistent behavior when adding an abort statement in the design view

modules/web/js/ballerina/components/suggestions-text.jsx
It should be an array of objects with a required name property.
=> Use the correct proptype for suggestions pool

modules/web/js/ballerina/ast/statements/continue-statement.js
This fixes the issue: https://github.com/ballerinalang/composer/issues/2439
=> Validating where the continue statement can be added in the lifeline

modules/web/js/ballerina/ast/connector-action.js, modules/web/js/ballerina/ast/expressions/action-invocation-expression.js, modules/web/js/ballerina/ast/function-definition.js, modules/web/js/ballerina/ast/resource-definition.js, modules/web/js/ballerina/components/assignment-statement.jsx, modules/web/js/ballerina/components/connector-declaraion.jsx, modules/web/js/ballerina/components/variable-definition-statement.jsx, modules/web/js/ballerina/visitors/dimension-calculator/assignment-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/position-calc/assignment-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/connector-declaration-position-calc.js, modules/web/js/ballerina/visitors/sizing-utils.js
With this PR, we fix the connector declaration rendering issue we had earlier which is addressed #2409, as well as the service level connector rendering issue addressed by #2470
=> Allowing connector declaration with assignment statement

modules/web/js/ballerina/components/transform-expanded.jsx, modules/web/js/ballerina/components/transform-statement-decorator.jsx
They were mistakenly taken to expanded component in the refactoring :(
=> Add onDropZoneActivate and onDropZoneDeactivate methods back to transform statement decorator

modules/web/css/ballerina-file-editor.css, modules/web/js/ballerina/components/annotation-attachment.jsx, modules/web/js/ballerina/components/annotation-attribute.jsx, modules/web/js/ballerina/components/annotation-container.jsx, modules/web/js/ballerina/env/annotation-definition.js, modules/web/js/ballerina/env/helpers/annotation-helper.js, modules/web/js/ballerina/env/package.js, modules/web/js/ballerina/visitors/symbol-table/ballerina-ast-root-visitor.js
Fixes : https://github.com/ballerinalang/composer/issues/2461 , https://github.com/ballerinalang/composer/issues/2440, https://github.com/ballerinalang/composer/issues/2351
=> Annotations ui fixes

modules/web/js/ballerina/components/lifeline.jsx, modules/web/js/ballerina/components/worker-declaration.jsx
This fixes issue: https://github.com/ballerinalang/composer/issues/2489
=> Truncating the worker name into its boundary

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/CompletionItemAccumulator.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/AbstractItemResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ItemResolverConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/TopLevelResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleStatementContextResolver.java
Completed the the content assist support task: https://github.com/ballerinalang/composer/issues/2377
=> Added Content assist for XML namespace and XML attribute reference

modules/web/js/ballerina/components/transform-expanded.jsx, modules/web/js/ballerina/components/transform-render.js
1. Allow to map "any" type in the transform
2. Recursion same type as a property type
=> fix transform issues

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/filters/PackageActionAndFunctionFilter.java
=> Fix issue No: 2468

modules/web/js/ballerina/components/reply-statement.jsx
=> Fix issue No: 2330

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/GlobalScopeResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ItemResolverConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ResolveCommandExecutor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/TopLevelResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleTypeNameContextResolver.java
With this Issue
Resolves #2457 
Fixing the incomplete templates for catch and struct
=> Resolves Issue No: 2457

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/filters/PackageActionAndFunctionFilter.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/CallableUnitBodyContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/DefaultResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ItemResolverConstants.java
With this PR
Resolves #2454 
Resolves #2452
=> Fixing suggestion issues

modules/web/js/ballerina/components/transform-expanded.jsx, modules/web/js/ballerina/components/transform-render.js, modules/web/js/ballerina/components/transform-statement-decorator.jsx, modules/web/js/ballerina/views/design-view.jsx
As all the tabs are present in the DOM we have to use a container specific to each mapper instance.
=> Make transform expanded view work when rendered in multiple tabs

modules/web/js/ballerina/ast/statements/assignment-statement.js, modules/web/js/ballerina/ast/statements/variable-definition-statement.js
This fixes issue: https://github.com/ballerinalang/composer/issues/2517
=> Fixing the issue when adding json and struct field access variables

modules/web/js/expression-editor/completer-factory.js, modules/web/js/expression-editor/expression-editor-utils.js
Fixing issue: https://github.com/ballerinalang/composer/issues/2516
=> Add completers for default scenario in Expression editor

modules/web/js/ballerina/tool-palette/tool-group-view.jsx
=> Fix Issue No:2543

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/AbstractItemResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ServiceContextResolver.java
With this PR, resolves the content suggestion issues at the service context level
=> Service level context issues fix

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/web/js/ballerina/ast/parameter-definition.js
Reverts ballerinalang/composer#2588
=> Revert "Fixing array params."

modules/web/css/ballerina-file-editor.css, modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/js/ballerina/views/source-view.jsx
=> Source view can be scrolled to the very bootom when the console is displayed

modules/web/js/ballerina/item-provider/initial-definitions.js
Fixes: https://github.com/ballerinalang/composer/issues/2610
=> Adding tool tip description for Namespace construct

modules/web/index.html, modules/web/js/welcome-page/first-launch-welcome.js, modules/web/js/welcome-page/welcome.jsx, modules/web/package.json
Fixes : https://github.com/ballerinalang/composer/issues/2593
=> Version upgrade. Generalized user-guide url.

modules/web/js/ballerina/ast/default-ballerina-ast-factory.js
Fix the issue: https://github.com/ballerinalang/composer/issues/2624
=> Fix the issue #2624

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/AbstractItemResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/GlobalScopeResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ItemResolverConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ResolveCommandExecutor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleAnnotationBodyContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleAttachmentPointContextResolver.java
=> Fixing Issue No: 2493

modules/web/js/ballerina/components/panel-decorator.jsx
=> Fix issue No: 2605

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/CompletionItemAccumulator.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/filters/StatementTemplateFilter.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/CallableUnitBodyContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ItemResolverConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ResolveCommandExecutor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleExpressionVariableDefStatementContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleTransformStatementBodyContextResolver.java
Resolves #2449 , #2450 
Need to get https://github.com/ballerinalang/ballerina/pull/3106 merged as well
=> Fix issues of content assist

modules/web/js/ballerina/ast/statements/trycatch-statement.js, modules/web/js/ballerina/components/catch-statement.jsx, modules/web/js/ballerina/components/try-catch-statement.css, modules/web/js/ballerina/components/try-statement.jsx
=> Fix issue No 2649

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangExpressionModelBuilder.java
=> Fix Issue 2298

modules/web/js/ballerina/ast/expressions/action-invocation-expression.js, modules/web/js/ballerina/ast/expressions/expression.js, modules/web/js/ballerina/ast/expressions/lambda-expression.js, modules/web/js/ballerina/ast/statements/assignment-statement.js, modules/web/js/ballerina/ast/statements/variable-definition-statement.js, modules/web/js/ballerina/components/assignment-statement.jsx, modules/web/js/ballerina/components/function-definition.jsx, modules/web/js/ballerina/components/statement-decorator.jsx, modules/web/js/ballerina/components/utils/tag-component.jsx, modules/web/js/ballerina/components/variable-definition-statement.jsx, modules/web/js/ballerina/visitors/annotation-rendering-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/assignment-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/lambda-expression-dimension-calculator-visitor.js, modules/web/js/ballerina/visitors/dimension-calculator/variable-definition-statement-dimension-calc.js, modules/web/js/ballerina/visitors/position-calc/assignment-statement-position-calc.js, modules/web/js/ballerina/visitors/position-calc/function-definition-position-calc.js, modules/web/js/ballerina/visitors/position-calc/lambda-expression-position-calc.js, modules/web/js/ballerina/visitors/position-calc/utils.js, modules/web/js/ballerina/visitors/sizing-utils.js, modules/web/js/ballerina/visitors/source-gen/action-invocation-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/assignment-statement-visitor.js, modules/web/js/ballerina/visitors/source-gen/function-definition-visitor.js
works for basic iterative functions. eg:-
```
function main (string[] args) {
x = a.apply(function(){
a = b;
int s = b;
});
}
```
=> Lambda ui for var def and iterative functions.

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/LangServerManager.java
Builtin packages are loaded at first time only, then it is retrieved from cache.
=> Cached the builtin packages.

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/web/js/ballerina/ast/default-ballerina-ast-factory.js
=> Fix Issue 2648

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/ast/function-definition.js, modules/web/js/ballerina/visitors/source-gen/function-definition-visitor.js, modules/web/js/tests/resources/modules/ballerina-core/src/test/resources/lang/functions/function-pointers.bal
this requires core PR ballerinalang/ballerina#3136
=> Adding returns keyword

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/filters/PackageActionAndFunctionFilter.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/AbstractItemResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleExpressionVariableDefStatementContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleStatementContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/parsercontext/ParserRuleVariableDefinitionStatementContextResolver.java, modules/web/js/ballerina/ast/default-ballerina-ast-factory.js, modules/web/js/ballerina/ast/expressions/action-invocation-expression.js, modules/web/js/ballerina/components/action-invocation-statement.jsx, modules/web/js/ballerina/components/assignment-statement.jsx, modules/web/js/ballerina/components/variable-definition-statement.jsx
This is to tally the composer action invocation to the ballerina run time revamp for the action invocation. 
In order to get this PR function properly we need to get the following PRs merged at Ballerina run time
- https://github.com/ballerinalang/ballerina/pull/3100
- https://github.com/ballerinalang/ballerina/pull/3107
=> Initial refactor for action invocation Revamp

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapper.java, modules/services/workspace-service/src/test/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapperTest.java, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/http-configuration.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/invalid-http-schemes.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/multiple-http-methods.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-1.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-3.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-4.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-5.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/http-configuration.json, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/invalid-http-schemes.json, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/multiple-http-methods.json, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/usecase-4.json, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/usecase-5.json, modules/web/js/ballerina/ast/default-ballerina-ast-factory.js, modules/web/js/ballerina/ast/resource-definition.js, modules/web/js/ballerina/views/swagger-view.jsx, modules/web/js/ballerina/visitors/source-gen/b-value-visitor.js, modules/web/js/swagger-parser/swagger-parser.js
Depends on https://github.com/ballerinalang/ballerina/pull/3108/
=> Modified swagger gen and swagger to bal merge for @http:resourceConfig

modules/web/js/ballerina/ast/ballerina-ast-deserializer.js, modules/web/js/ballerina/ast/node.js, modules/web/js/ballerina/ast/statements/catch-statement.js, modules/web/js/ballerina/ast/statements/if-else-statement.js, modules/web/js/ballerina/ast/statements/if-statement.js, modules/web/js/ballerina/ast/statements/statement.js, modules/web/js/ballerina/ast/statements/trycatch-statement.js, modules/web/js/ballerina/ast/statements/while-statement.js, modules/web/js/ballerina/utils/design-view-completer-factory.js, modules/web/js/ballerina/utils/design-view-completer-utils.js, modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/js/expression-editor/expression-editor-utils.js
=> Embed LangServer in Design view

integration-tests/pom.xml, integration-tests/ui-integration-tests/pom.xml, integration-tests/ui-integration-tests/webpack.config.js, modules/web/js/tests/js/spec/LanguageServerTest.js, modules/web/webpack.config.js
=> Fixing build failure.

modules/web/js/ballerina/components/transform/tree.css, modules/web/js/ballerina/components/transform/variable-endpoint.css, modules/web/js/ballerina/components/transform/variable-endpoint.jsx
Added tree using CSS
connected point improvements
=> Transform view UX improvements 

modules/web/js/ballerina/components/transform-expanded.jsx, modules/web/js/ballerina/components/transform-node-manager.js, modules/web/js/ballerina/components/transform-render.js, modules/web/js/ballerina/components/transform/function.jsx, modules/web/js/ballerina/components/transform/tree.jsx, modules/web/js/ballerina/components/transform/variable-endpoint.jsx
Also initial implementation of folding structs
=> Transform code refactor

modules/web/js/debugger/debugger.css, modules/web/js/debugger/frames/frames.css, modules/web/js/debugger/frames/frames.jsx, modules/web/js/debugger/frames/index.js, modules/web/package.json
* New UI for debugger variables
* Migrate Frames component to React
=> Migrate debugger variables UI to React

modules/web/js/ballerina/components/transform/function.jsx, modules/web/js/ballerina/components/transform/variable-endpoint.jsx
* fixed issue where functions can't be removed.
* fixed issue where connect points are removed on clicking variable name.
=> Transform bug fixes

modules/web/index.html, modules/web/js/debugger/debugger.css, modules/web/js/debugger/tools.js
Fixes https://github.com/ballerinalang/composer/issues/986
=> Add message to remote debug UI, fixes #986

modules/web/js/ballerina/toolbar/toolbar-callback-functions.js, modules/web/js/ballerina/toolbar/toolbar-definitions.js, modules/web/js/ballerina/toolbar/toolbar.css
Fixes https://github.com/ballerinalang/composer/issues/2864
Fixes https://github.com/ballerinalang/composer/issues/2869
=> Using css parent selectors for the debugging toolbar

modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram/views/default/components/transform/transform-node-manager.js, modules/web/js/ballerina/diagram/views/default/components/transform/transform-render.js
Fixes : https://github.com/ballerinalang/composer/issues/2971
=> Avoid invalid mappings based on the type lattice

modules/web/index.html, modules/web/js/debugger/tools.js, modules/web/js/launcher/launcher.js
Fixed issue: https://github.com/ballerinalang/composer/issues/2789
=> Remove app argument config window to have add argument button

modules/web/js/debugger/frames/frames.jsx
fixes https://github.com/ballerinalang/composer/issues/2958
=> Show map variables in variable tree

modules/web/js/ballerina/diagram/views/default/position-visitors/transaction-aborted-statement-position-calc.js
=> Fix Issue No: 3006

modules/web/js/ballerina/diagram/views/default/dimention-visitors/trycatch-dimension-calculator-visitor.js
Fix the issue: https://github.com/ballerinalang/composer/issues/3003
=> Fix the issue where text adjustment of catch block doesn't work properly

modules/web/index.html
Fixes https://github.com/ballerinalang/composer/issues/2980
=> Added sample url for remote debug dialog

modules/web/js/ballerina/diagram/views/compact/dimension-visitors/aborted-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/catch-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/committed-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/else-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/elseif-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/failed-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/finally-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/if-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/transaction-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/try-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/dimension-visitors/while-statement-dimension-calculator-visitor.js, modules/web/js/ballerina/diagram/views/compact/sizing-util.js
=> Fix Issue No: 2945

modules/web/js/ballerina/ast/expressions/action-invocation-expression.js
=> Fix Issue No: 2919

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LaunchManager.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LauncherConstants.java, modules/web/css/styles.css, modules/web/js/launcher/console.js, modules/web/package.json
related issue: https://github.com/ballerinalang/composer/issues/2975
=> Improve the launcher console to show URL as a link, fixes#2975

modules/web/js/ballerina/diagram/views/default/components/transform/function.jsx, modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.css, modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram/views/default/components/transform/transform-render.js
This makes the size of the scroll bar same across browsers and other components can be styled to look same across browsers.
=> Use a custom scroller in transform expanded view

modules/web/js/ballerina/ast/ballerina-ast-root.js, modules/web/js/ballerina/ast/global-variable-definition.js, modules/web/js/ballerina/ast/service-definition.js, modules/web/js/ballerina/diagram/views/default/components/global-item.jsx, modules/web/js/ballerina/diagram/views/default/components/globals-expanded.jsx
=> Fix Issue No: 2916

modules/web/js/ballerina/ast/ballerina-ast-root.js, modules/web/js/ballerina/ast/statements/catch-statement.js, modules/web/js/ballerina/diagram/views/default/components/try-catch-statement.jsx
fixes: https://github.com/ballerinalang/composer/issues/2920
=> Fix the issue with catch statement defaultly adding wrong expression and automatically import errors package

modules/web/js/workspace/manager.js
=> Fix Issue No: 1959

modules/web/css/sequence_diagram/sequenced-styles.css, modules/web/js/ballerina/diagram/views/default/components/action-box.jsx, modules/web/js/ballerina/diagram/views/default/components/block-statement-decorator.jsx, modules/web/js/ballerina/diagram/views/default/components/catch-statement.jsx
fixes https://github.com/ballerinalang/composer/issues/2925
=> Disabled delete when there is only one catch statement with the try catch statement

modules/web/js/ballerina/diagram/views/default/components/action-box.jsx
fixes https://github.com/ballerinalang/composer/issues/2976
=> Fix the issue with user can apply break point to worker header

modules/web/js/ballerina/diagram/views/default/components/transform/function.css, modules/web/js/ballerina/diagram/views/default/components/transform/function.jsx, modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.css, modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram/views/default/components/transform/transform-render.js, modules/web/js/ballerina/diagram/views/default/components/transform/transform-statement.css, modules/web/js/ballerina/diagram/views/default/components/transform/variable-endpoint.css, modules/web/js/ballerina/diagram/views/default/components/transform/variable-endpoint.jsx
In transform-expanded view when a connection is dragged on to a target the cursor shows if the connection is valid.
=> Show whether a possible connection is valid on mouse over

modules/web/js/ballerina/diagram/views/default/components/transform/transform-node-mapper.js, modules/web/js/ballerina/diagram/views/default/components/transform/variable-endpoint.jsx
Also 'operator' -> 'function' in event title
=> Check for empty var def statement as well

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/LangServerManager.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/SymbolInfo.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/TreeVisitor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/CallableUnitBodyContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/GlobalScopeResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/ResolveCommandExecutor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/suggetions/CapturePossibleTokenStrategy.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/suggetions/SuggestionsFilter.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/suggetions/SuggestionsFilterDataModel.java
This includes the initial refactoring changes for the language server
=> Language server refactor

modules/web/js/ballerina/views/source-editor.jsx, modules/web/src/core/editor/views/EditorTabTitle.jsx, modules/web/src/core/editor/views/EditorTabs.jsx
Fix split view tab title style.
Fix tab title dirty state change upon tab change.
Fix empty undo stack item upon tab change.
=> Fixing a few issues in Split-View

modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.css, modules/web/js/ballerina/diagram/views/default/components/transform/variable-endpoint.css
Text in icons are properly centered. Mouse over targests when dragging fixed.
=> Fix small glitches in transform expanded view

modules/web/scss/modules/ballerina-editor.scss
=> Removed circle around array badge in annotations.

modules/web/src/plugins/try-it/views/http-client.jsx
Fixes https://github.com/ballerinalang/composer/issues/3137
=> Added placeholders for headers in try-it client.

modules/web/js/ballerina/diagram/views/default/components/transform/function.css, modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.css, modules/web/js/ballerina/diagram/views/default/components/transform/transform-statement.css, modules/web/js/ballerina/diagram/views/default/components/transform/variable-endpoint.css, modules/web/js/ballerina/diagram/views/default/components/transform/variable-endpoint.jsx, modules/web/src/index.js
Fixed more glitches in transform expanded view
=> Changed order of imports so we can override css rules from libraries we add

modules/web/src/core/view/context-menu/styles.scss, modules/web/src/plugins/try-it/views/http-client.jsx, modules/web/src/plugins/try-it/views/http-client.scss, modules/web/src/plugins/try-it/views/try-it-container.scss
=> Release fixes part02

modules/web/scss/modules/ballerina-editor.scss, modules/web/scss/modules/editor-tabs.scss, modules/web/scss/modules/layout.scss, modules/web/src/core/layout/components/App.jsx
=> Fixed main vertical scroll bar to appear correctly

modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/scss/modules/ballerina-editor.scss, modules/web/src/core/editor/views/EditorTabs.jsx
https://github.com/ballerinalang/composer/pull/3197 needs to be merged before merging this.
=> Added close split-view button.

modules/web/pom.xml
We can use this when developing as we anyway build it by `npm run dev`
=> Skip building client side code by `-Pskip-client`

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-factory.js, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-manager.js
- fix transform new variable support
- improve transform factory to use fragment parser
=> fix transform new variable support

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-factory.js, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-manager.js, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-mapper.js, modules/web/js/ballerina/env/environment.js, modules/web/js/ballerina/utils/transform-utils.js
- Get default value for replacing args during connection remove
- Remove node output connections
=> Transform statement improvements

modules/web/js/ballerina/utils/react-try-catch-batching-strategy.js, modules/web/js/ballerina/views/ballerina-file-editor.jsx
Based on 
https://engineering.classdojo.com/blog/2016/12/10/catching-react-errors/
=> Add try-catch enabled fail safe batching strategy

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapper.java, modules/web/js/ballerina/diagram2/views/default/components/nodes/annotation-attachment-attribute-node.jsx, modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/js/ballerina/views/swagger-view.jsx
Fixes for findbug.
Annotation literal length to auto increase.
Fixed openning swagger view.
=> Added fixes for annotations and swagger related components.

modules/web/js/ballerina/diagram2/views/default/components/transform/operator.css, modules/web/js/ballerina/diagram2/views/default/components/transform/operator.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-statement.css
=> Moved transform operator related css to operator.css

modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/model/tree-util.js, modules/web/js/ballerina/model/tree/block-node.js, modules/web/js/ballerina/tool-palette/tool-palette-view.jsx, modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/js/langserver/lang-server-client-controller.js
Also drag drop function invocations
=> Use lang server to create temp variable names

modules/web/js/ballerina/model/source-gen.js, modules/web/source-gen/source-gen-template.js, modules/web/source-gen/tree.g
Reverts ballerinalang/composer#3517
=> Revert "Improving source gen : constrained types, annot, try, catch, xml..."

modules/web/js/ballerina/ast/default-ast-factory.js, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/model/transform-factory.js, modules/web/js/ballerina/tool-palette/item-provider/operator-tools.js, modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/js/ballerina/views/design-view.jsx, modules/web/js/ballerina/views/source-view.jsx, modules/web/src/plugins/ballerina/editor/Editor.jsx
* Redraw transform arrows on panel resizes
* Use semicolon in code templates
=> Transform improvements

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/model/transform-factory.js, modules/web/js/ballerina/model/tree/transform-node.js, modules/web/js/ballerina/tool-palette/tool-palette-view.jsx
No need for the transform node to have those defined by itself
=> Use acceptDrop from block node and function invocation from DefaultNodeFactory

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFragmentParser.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFragmentParserConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java, modules/web/js/ballerina/diagram2/views/default/components/nodes/fork-join-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/retry-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/transaction-node.jsx, modules/web/js/ballerina/diagram2/views/default/sizing-util.js, modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/model/tree-builder.js, modules/web/js/ballerina/model/tree-util.js, modules/web/js/ballerina/model/tree/transaction-node.js
=> Fix the issue with transaction block rendering and retry statement and adding statements to fork join

modules/web/js/ballerina/diagram2/views/default/components/nodes/service-transport-line.jsx, modules/web/js/ballerina/model/tree/node.js
Fixes issue https://github.com/ballerinalang/composer/issues/3715
=> Fixing issue when syncing nodes + UI positioning fixes

modules/web/js/ballerina/diagram2/views/default/components/nodes/compound-statement-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/fork-join-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/transaction-node.jsx
=> Added worker drop zone and the transaction inner drop zone

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/http-configuration.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/invalid-http-schemes.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/multiple-http-methods.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/multiple-resources.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-1.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-2.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-3.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-4.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-5.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/usecase-2.json, modules/web/js/ballerina/swagger-parser/swagger-parser.js, modules/web/js/ballerina/views/swagger-view.jsx, modules/web/scss/modules/ballerina-editor.scss
Fixes https://github.com/ballerinalang/composer/issues/3626 , https://github.com/ballerinalang/composer/issues/3646
=> Fixed support for default http methods, Hiding swagger try-it.

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/TreeVisitor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/resolvers/AbstractItemResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/suggetions/SuggestionsFilter.java
=> Fix Issues #3578, #3731

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/util/WorkspaceUtils.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/utils/BallerinaProgramContentProvider.java, modules/web/js/ballerina/diagram2/views/default/components/decorators/connector-declaration-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/function-node.jsx
=> Fix Issue #3707

modules/web/js/ballerina/diagram2/views/default/components/nodes/worker-send-node.jsx, modules/web/js/ballerina/diagram2/views/default/worker-invocation-arrow-position-util.js, modules/web/js/ballerina/diagram2/views/default/worker-invocation-sync-util.js, modules/web/js/ballerina/diagram2/visitors/clean.js, modules/web/js/ballerina/model/tree-util.js
=> Fix Issue #3607

modules/web/js/ballerina/diagram2/views/default/components/nodes/compound-statement-decorator.css, modules/web/js/ballerina/diagram2/views/default/components/nodes/compound-statement-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/sizing-util.js
Resolves #3711 
Resolves #3704
=> Fix Issue #3711 #3704

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/LangServerManager.java
=> Fix for Issue #3628

modules/web/js/ballerina/diagram2/views/default/components/nodes/catch-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/try-node.jsx
=> Added multiple block adding capability to try catch statement

modules/web/js/ballerina/tool-palette/tool-group-view.jsx, modules/web/src/core/editor/plugin.js, modules/web/src/core/layout/components/LeftPanel.jsx, modules/web/src/core/toolbar/components/Tool.jsx, modules/web/src/core/workspace/dialogs/FileSaveDialog.jsx, modules/web/src/core/workspace/plugin.js, modules/web/src/plugins/ballerina/plugin.js, modules/web/src/plugins/debugger/plugin.js
https://github.com/ballerinalang/composer/issues/3746
https://github.com/ballerinalang/composer/issues/3723
https://github.com/ballerinalang/composer/issues/3465
https://github.com/ballerinalang/composer/issues/3585
https://github.com/ballerinalang/composer/issues/3597
=> Fixes for Issues: 3476, 3723, 3465, 3585, 3897

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/Workspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/cloud/CloudWorkspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/local/LocalFSWorkspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/WorkspaceService.java, modules/web/js/api-client/api-client.js, modules/web/src/core/layout/components/LeftPanel.jsx, modules/web/src/core/view/scroll-bars/ScrollBarsWithContextAPI.jsx, modules/web/src/core/view/tree-view/FileTree.jsx, modules/web/src/core/view/tree-view/TreeNode.jsx, modules/web/src/core/workspace/dialogs/FileOpenDialog.jsx, modules/web/src/core/workspace/dialogs/FileSaveDialog.jsx, modules/web/src/core/workspace/dialogs/FolderOpenDialog.jsx
Improve file tree and introduce a new component with scrolling API
=> Make file/folder open/save wizards remember history and scroll to that node upon open

modules/web/js/ballerina/diagram2/views/default/components/nodes/compound-statement-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/fork-join-node.jsx, modules/web/js/ballerina/diagram2/views/default/positioning-util.js, modules/web/js/ballerina/diagram2/views/default/sizing-util.js, modules/web/js/ballerina/model/source-gen.js, modules/web/js/ballerina/model/tree/node.js, modules/web/source-gen/tree.g
=> Fix rendering issue in fork join and added block delete for fork join

modules/web/js/ballerina/tool-palette/item-provider/default-tools.js
Fixes
https://github.com/ballerinalang/composer/issues/3813
https://github.com/ballerinalang/composer/issues/3816
=> Fix typo in tooltips for tool-pallete.

modules/web/js/ballerina/model/default-node-factory.js
=> Fix Issue #3827

modules/web/js/ballerina/visitors/sync-line-numbers.js, modules/web/src/plugins/debugger/views/BreakpointHoc.jsx, modules/web/src/plugins/debugger/views/DebuggerHoc.jsx
Resolves https://github.com/ballerinalang/composer/issues/3695
=> Fix splitview breakpoints in multiple files

modules/web/js/ballerina/tool-palette/item-provider/default-tools.js
=> Fix typos of words sticking together in tool tips

modules/web/js/ballerina/views/swagger-view.jsx
Fixes https://github.com/ballerinalang/composer/issues/3649
=> Fixed switching to souce view when in swagger view.

modules/web/src/core/view/tree-view/TreeNode.jsx
TODO: We need to improve plugin arch to contribute supported extension
types for new file/save file wizards similar to editor contribs.
Fixes
https://github.com/ballerinalang/composer/issues/3651
=> Implicitly add bal extension while adding files from tree

modules/web/js/ballerina/diagram2/views/default/components/utils/statement-property-item-selector.jsx, modules/web/js/ballerina/diagram2/visitors/clean.js
Resolves #3853 
Resolves #3850
=> Fix Issue #3853

modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/server-connector-properties-form.jsx, modules/web/js/ballerina/diagram2/views/default/positioning-util.js, modules/web/js/ballerina/model/default-node-factory.js
=> Make the last add resource button work on websocket services

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/web/js/ballerina/swagger-parser/swagger-parser.js, modules/web/src/plugins/import-swagger/dialogs/import-swagger-dialog.jsx, modules/web/src/plugins/import-swagger/plugin.js
Fixes https://github.com/ballerinalang/composer/issues/3823
=> Fixed issues in swagger import. Supported array types params in swagger.

modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/views/ballerina-file-editor.jsx
=> Fix Issue #3897

modules/web/js/ballerina/diagram2/views/default/sizing-util.js
=> Fix Issue #3887

modules/web/js/ballerina/diagram2/views/default/components/utils/connector-properties.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/server-connector-properties-form.jsx
Fixes https://github.com/ballerinalang/composer/issues/3603
=> Fixed styling issues of the property window

modules/web/js/ballerina/model/tree/resource-node.js, modules/web/src/core/editor/handlers.js, modules/web/src/core/editor/plugin.js, modules/web/src/core/layout/components/App.jsx, modules/web/src/core/layout/components/utils.js, modules/web/src/core/view/tree-view/TreeNode.jsx, modules/web/src/core/view/tree-view/menu.js, modules/web/src/core/workspace/components/ExplorerItem.jsx, modules/web/src/plugins/try-it/plugin.js, modules/web/src/plugins/try-it/views/http-client.jsx, modules/web/src/plugins/try-it/views/http-client.scss
Fixes https://github.com/ballerinalang/composer/issues/3862
Fixes https://github.com/ballerinalang/composer/issues/3664
Fixes https://github.com/ballerinalang/composer/issues/3678
Fixes https://github.com/ballerinalang/composer/issues/3672
=> Fixes for Try-It

modules/web/js/ballerina/diagram2/views/default/components/nodes/top-level-nodes.jsx
=> Fix Issue #3874

modules/web/js/ballerina/diagram2/views/default/components/utils/connector-properties.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/server-connector-properties-form.jsx, modules/web/js/ballerina/env/helpers/connector-helper.js
Fixes https://github.com/ballerinalang/composer/issues/3844
=> Rendering the property window with a message if there are no properties + not adding properties of the connector if they are not provided

modules/web/src/plugins/try-it/views/http-client.jsx, modules/web/src/plugins/try-it/views/http-client.scss, modules/web/src/plugins/try-it/views/try-it-container.scss
=> [fixed #3859 #3907] styling changes to tryout function

modules/web/js/ballerina/diagram2/views/default/components/utils/connector-properties.jsx
Fixes https://github.com/ballerinalang/composer/issues/3842
=> Renaming the client connector configuration pop ups with respective client connector

modules/web/js/ballerina/drag-drop/drop-target.js, modules/web/js/ballerina/model/tree/abort-node.js
=> Added parent filtering for abort node

modules/web/js/ballerina/model/tree/compilation-unit-node.js
https://github.com/ballerinalang/composer/issues/3868
=> Fix target index calc for imports & globals

modules/web/src/core/editor/plugin.js, modules/web/src/core/editor/views/EditorTabTitle.jsx, modules/web/src/core/editor/views/EditorTabs.jsx, modules/web/src/core/view/tree-view/TreeNode.jsx
Includes the fix for
https://github.com/ballerinalang/composer/issues/3920
=> Fixes to tree editing & editor tabs - tab close handling

modules/web/js/ballerina/diagram2/views/default/components/nodes/worker-node.jsx
=> Fix Issue #3794

modules/web/js/ballerina/diagram2/views/default/components/decorators/lifeline.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/worker-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/3795
=> Fixing the issue when jumping to source from workers 

modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx
Fixes https://github.com/ballerinalang/composer/issues/3713
=> Removed reference for the old diagram folder.

modules/web/font/font-ballerina/icons/next.svg, modules/web/js/ballerina/diagram2/views/default/components/nodes/next-node.jsx, modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/model/tree/next-node.js, modules/web/js/ballerina/tool-palette/item-provider/default-tools.js
=> Added support for next node rendering

modules/web/src/plugins/debugger/views/console-decorators/http-service-decorator.jsx, modules/web/src/plugins/import-swagger/constants.js, modules/web/src/plugins/import-swagger/dialogs/import-swagger-dialog.jsx, modules/web/src/plugins/import-swagger/menus.js
Fixes https://github.com/ballerinalang/composer/issues/3979
Fixes https://github.com/ballerinalang/composer/issues/3430
Fixes https://github.com/ballerinalang/composer/issues/3980
=> Fixed several UI issues.

modules/web/src/plugins/debugger/LaunchManager/LaunchManager.js, modules/web/src/plugins/debugger/views/console-decorators/http-service-decorator.jsx, modules/web/src/plugins/try-it/constants.js, modules/web/src/plugins/try-it/plugin.js
Fixes https://github.com/ballerinalang/composer/issues/3811
Fixes https://github.com/ballerinalang/composer/issues/3128
=> Fixed showing try-it for services only.

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/3906
=> Providing an error when trying to add invalid values and bType variables to a struct

modules/web/src/plugins/try-it/plugin.js
Fixes https://github.com/ballerinalang/composer/issues/3972
=> Fixed try-it tooltip coming undefined

modules/web/js/ballerina/model/tree/retry-node.js
=> Added parent filtering to retry node

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFileRestService.java
https://github.com/ballerinalang/composer/issues/3974
=> Fix validate not returning errors for persisted files

modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx
Fixes https://github.com/ballerinalang/composer/issues/3989
=> Removing the prop window being closed when clicked outside

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/http-configuration.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/invalid-http-schemes.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/multiple-http-methods.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/multiple-resources.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-4.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/input/usecase-5.bal, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/usecase-4.json, modules/services/workspace-service/src/test/resources/samples/swagger/ballerina-to-swagger/output/usecase-5.json, modules/web/js/ballerina/swagger-parser/swagger-parser.js
Fixes https://github.com/ballerinalang/composer/issues/3661
=> Removed @http:PathParam and @http:QueryParam support.

modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx
Fixes https://github.com/ballerinalang/composer/issues/3992
Fixes https://github.com/ballerinalang/composer/issues/4002
=> Fixing the intermittent issue of the prop window becoming unresponsive + Changing the icon to default if it cannot be clicked in the breadcrumb

modules/web/js/ballerina/diagram2/views/default/components/nodes/compound-statement-decorator.jsx, modules/web/src/core/editor/plugin.js, modules/web/src/core/workspace/model/file.js
Fixes https://github.com/ballerinalang/composer/issues/3987
Also Fixes https://github.com/ballerinalang/composer/issues/4023
=> Update active editor ID when file is persisted for the first time & fix compound stmt drop zone overlap

modules/web/js/ballerina/diagram2/views/default/components/nodes/global-item.jsx
Fixes https://github.com/ballerinalang/composer/issues/4029
=> Fixing the issue when assigning values for global variables already added

modules/web/js/ballerina/diagram2/views/default/sizing-util.js, modules/web/scss/modules/ballerina-editor.scss
Fixes https://github.com/ballerinalang/composer/issues/4024
=> Set fixed height for annotation contents.

modules/web/src/plugins/import-swagger/plugin.js
Fixes https://github.com/ballerinalang/composer/issues/4020
=> Fixed showing invalid message when importing invalid swagger definition.

modules/web/js/ballerina/diagram2/views/default/components/nodes/annotation-attachment-attribute-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/annotation-attachment-attribute-variable-ref-node.jsx, modules/web/js/ballerina/model/tree/annotation-attachment-attribute-value-node.js
Fixes https://github.com/ballerinalang/composer/issues/4026
=> Added support for variable refs in annotations for design view.

modules/web/js/ballerina/drag-drop/drop-target.js, modules/web/js/ballerina/model/tree/abort-node.js, modules/web/js/ballerina/model/tree/block-node.js
=> Fix Issue #4033

modules/services/workspace-service/src/test/resources/samples/tryit/request/getQuoteJSON.json, modules/services/workspace-service/src/test/resources/samples/tryit/response/getQuoteJSON.json
Fixes build failure - org.wso2.msf4j.example.exception.SymbolNotFoundException: Symbol BAR not found
=> Fixed failing test cases for try-it client.

modules/web/js/ballerina/views/ballerina-file-editor.jsx
For source modifications or undo/redo invocations
while in split view, wait (500ms & 100ms respectively)
after final keypress of the key streak.
=> Debounce re-render during split mode source changes & undo/redo

modules/web/js/ballerina/model/tree-util.js
=> Fix the issue with renaming return parameter

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/3888
=> Calculating struct body content with annotation height.

modules/web/js/ballerina/model/tree-util.js, modules/web/js/ballerina/model/tree/abstract-tree/package-declaration-node.js, modules/web/js/ballerina/views/ballerina-file-editor.jsx, modules/web/src/plugins/debugger/views/BreakpointHoc.jsx, modules/web/src/plugins/debugger/views/DebuggerHoc.jsx
* Added util function to get package name
=> Fix debugging with packages

modules/web/js/ballerina/diagram2/views/default/components/transform/tree.css, modules/web/js/ballerina/diagram2/views/default/components/transform/tree.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.css, modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.jsx
=> Transform tree view improvements

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-definition-item.jsx
fixes https://github.com/ballerinalang/composer/issues/4112
=> Support for UserDefinedType and ArrayType in struct definition

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.css, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/tree.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.css, modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.jsx
Also fixed right marging for endpoints
=> Add horizontal scroll to transform expanded view

modules/web/js/ballerina/utils/ace-mode.js
=> Added next keyword to syntax highlighting

modules/web/js/ballerina/model/tree/block-node.js, modules/web/js/ballerina/model/tree/next-node.js
=> Fix the issue where next can be added before any statement

modules/web/js/ballerina/utils/ace-mode.js, modules/web/src/core/editor/plugin.js
Fix following issues
https://github.com/ballerinalang/composer/issues/4167
https://github.com/ballerinalang/composer/issues/4015
=> Fix issues - 4167 & 4015

modules/web/src/plugins/debugger/views/DebuggerPanel.jsx
=> Fix the issue with tooltip

modules/services/workspace-service/src/test/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelTest.java, modules/web/js/tests/js/spec/transform-test.js, modules/web/js/tests/resources/transform/direct-mapping/direct-with-args-expected.bal, modules/web/js/tests/resources/transform/direct-mapping/direct-with-args.bal, modules/web/js/tests/resources/transform/direct-mapping/direct-with-primitive-vars-expected.bal, modules/web/js/tests/resources/transform/direct-mapping/direct-with-primitive-vars.bal
- Contains tests for basic direct mappings
=> Transform Automation Test Suite

modules/web/js/ballerina/diagram2/views/default/components/nodes/top-level-nodes.jsx
=> Fix removing package from split view doesn't render UI

modules/web/js/expression-editor/expression-editor-utils.js
=> Fix adding invalid content doesn't show an error on composer

modules/web/js/ballerina/diagram2/views/default/components/decorators/lifeline.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/worker-node.jsx
=> Added name editing functionlity for workers

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/completion/filters/PackageActionAndFunctionFilter.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/completion/resolvers/AbstractItemResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/completion/resolvers/parsercontext/ParserRuleStatementContextResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/completion/resolvers/parsercontext/ParserRuleVariableDefinitionStatementContextResolver.java
With the added functionality, bound functions can be resolved as follows.
Resolves #4126
=> Adding bound function resolving for language server

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFileRestService.java, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-manager.js, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-mapper.js, modules/web/js/ballerina/model/transform-factory.js, modules/web/js/tests/js/spec/transform/direct-mapping-creation-test.js, modules/web/js/tests/js/spec/transform/transform-test-utils.js, modules/web/js/type-lattice/operator-lattice.js
=> [Transform] Operand removal and test improvements

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/tryit/HttpTryItClient.java
Fixes https://github.com/ballerinalang/composer/issues/4147
=> Added default header for try-it service.

modules/web/js/ballerina/tool-palette/tool-palette-view.jsx
=> Transform tool-pallert operators made searchable

modules/web/js/ballerina/diagram2/views/default/components/nodes/connector-node.jsx, modules/web/js/ballerina/diagram2/views/default/error-rendering-util.js, modules/web/js/ballerina/diagram2/views/default/positioning-util.js, modules/web/js/ballerina/diagram2/views/default/sizing-util.js
Fixes https://github.com/ballerinalang/composer/issues/4274
=>  Allowing connector parameters to be rendered in design view + Rendering semantic errors for connector parameters

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/TreeVisitor.java
=> Fix Issue #4250

integration-tests/ui-integration-tests/src/test/assembly/bin.xml, integration-tests/ui-integration-tests/src/test/resources/ballerina-home/bin/composer, integration-tests/ui-integration-tests/src/test/resources/ballerina-home/bin/composer.bat, modules/services/workspace-service/deployment.yaml, modules/services/workspace-service/pom.xml, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/app/WorkspaceServiceRunner.java, modules/services/workspace-service/src/main/resources/deployment.yaml, modules/services/workspace-service/src/main/resources/netty-transports.yml, modules/services/workspace-service/src/test/resources/samples/tryit/response/addStock.json, modules/services/workspace-service/src/test/resources/samples/tryit/response/getMetaInformationForQuoteJSON.json
Fixes https://github.com/ballerinalang/composer/issues/67
Depends on https://github.com/ballerinalang/ballerina-parent/pull/63
=> Updated msf4j and changed needed for the updated.

modules/web/js/ballerina/model/tree-util.js
=> Fix Issue #4276

modules/web/js/api-client/api-client.js
=> Fix for struct fields not getting added when added manually

modules/web/src/plugins/export-diagram/dialogs/export-diagram-dialog.jsx, modules/web/src/plugins/export-diagram/menus.js
=> Fix the issue with diagram is not rendering fully

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/model/Function.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/util/WorkspaceUtils.java, modules/web/js/ballerina/env/function.js, modules/web/js/ballerina/tool-palette/tool-palette-view.jsx
Fixes https://github.com/ballerinalang/composer/issues/4304
=> Tool-palette should only show the public functions of the packages

modules/web/js/ballerina/diagram2/views/default/components/nodes/global-item.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/top-level-nodes.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/xmlns-node.jsx, modules/web/js/ballerina/diagram2/views/default/error-rendering-util.js, modules/web/js/ballerina/diagram2/views/default/positioning-util.js, modules/web/js/ballerina/diagram2/views/default/sizing-util.js, modules/web/js/ballerina/model/tree-builder.js, modules/web/js/ballerina/model/tree/compilation-unit-node.js
=> Implement global variable support for XML namespace

modules/web/js/ballerina/views/ballerina-file-editor.jsx
=> Fix the issue with block level variables

modules/web/js/ballerina/diagram2/views/default/components/nodes/if-node.jsx, modules/web/js/ballerina/model/default-node-factory.js, modules/web/src/plugins/export-diagram/dialogs/export-diagram-dialog.jsx
=> Fix export diagram dialog box style issue and if else default rendering

modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/tag-input.jsx
Fixes https://github.com/ballerinalang/composer/issues/4255
=> Adding values to tag inputs/array using enter and when separated by comma

modules/web/js/ballerina/diagram2/views/default/components/nodes/top-level-nodes.jsx
=> Added descrition to global variable placeholder

modules/web/js/ballerina/diagram2/views/default/components/nodes/connector-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/service-node.jsx
=> Fix to show an alert on adding constants in service and connector

modules/web/js/ballerina/diagram2/views/default/components/nodes/action-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/add-action-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/connector-node.jsx, modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/tool-palette/item-provider/default-tools.js
Fixes https://github.com/ballerinalang/composer/issues/4330
=> Add actions to Connector using an Add Action button

modules/web/js/ballerina/views/design-view.jsx
=> Fix the issue with split view and source view button icon

modules/web/js/ballerina/model/tree-util.js, modules/web/js/expression-editor/expression-editor-utils.js
=> Fix the issue with expression editor throw an error on removal of semicolon

modules/web/js/ballerina/diagram2/views/default/components/nodes/add-resource-definition.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/resource-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/service-definition.css, modules/web/js/ballerina/diagram2/views/default/components/nodes/service-transport-line.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/websocket-resource-select.jsx, modules/web/js/ballerina/model/default-node-factory.js, modules/web/js/ballerina/tool-palette/item-provider/default-tools.js, modules/web/js/ballerina/tool-palette/tool-palette-view.jsx, modules/web/scss/modules/ballerina-editor.scss
Fixes https://github.com/ballerinalang/composer/issues/4335
Fixes https://github.com/ballerinalang/composer/issues/4336
=> Server Connector tools for JMS, File (FTP and FS)

modules/web/src/core/workspace/components/ExplorerItem.jsx
Fixes https://github.com/ballerinalang/composer/issues/4342
=> Fix explorer node collapse issue when a nested file is open

modules/web/js/ballerina/diagram2/views/default/components/nodes/add-compound-block.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/if-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/multiblock-select.jsx
This will allow user to select which block to add from a drop down.
Fix #2092
=> Added if else multi block add drop down

modules/web/js/ballerina/diagram2/views/default/components/nodes/catch-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/if-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/transaction-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/try-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/multiblock-select.jsx
This will add multi block selection to try catch 
and transaction compound statement
=> Added multiblock select to transaction and try compound statements

modules/web/js/ballerina/diagram2/views/default/error-rendering-util.js
Fixes https://github.com/ballerinalang/composer/issues/4356
=> Showing all transformer semantic errors in design view together

modules/web/js/ballerina/diagram2/views/default/components/utils/connector-properties.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx
Fixes https://github.com/ballerinalang/composer/issues/4361
Fixes https://github.com/ballerinalang/composer/issues/4357
=> Fix issues with the property window

modules/web/js/ballerina/diagram2/views/default/components/utils/semantic-errors-popup.jsx
Fixes https://github.com/ballerinalang/composer/issues/4360
=> Fixing error line numbers in design view

modules/web/js/ballerina/model/source-gen.js, modules/web/js/tests/resources/parser/transformer-person.bal, modules/web/source-gen/tree.g
Fixing curly brace jumping when there is no name for the transformer.
=> Fixing transformer ws for no-name case.

modules/web/js/ballerina/diagram2/views/default/components/decorators/panel-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/transformer-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-statement.css, modules/web/js/ballerina/diagram2/views/default/sizing-util.js
=> Show transform node details

modules/web/js/ballerina/diagram2/views/default/components/decorators/panel-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/transformer-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transformer-node-details.jsx, modules/web/js/ballerina/diagram2/views/default/sizing-util.js
=> Make transformer name edittable

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/completion/filters/PackageActionAndFunctionFilter.java
=> Add completion support for connector actions and functions

modules/web/js/ballerina/model/lambda-util.js, modules/web/js/ballerina/utils/design-view-completer-factory.js, modules/web/js/expression-editor/expression-editor-utils.js
1) Fix lambda order revering bug.
2) Add lambda auto complete.
=> Lambda fixes

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFragmentParser.java
=> Fix Issue #4431

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-mapper.js, modules/web/js/ballerina/diagram2/views/default/sizing-util.js
* Do not show () when a transformer has no name
* Fix connections from variables not rendering
=> Transform display fixes

modules/web/js/ballerina/diagram2/views/default/components/utils/websocket-resource-select.jsx
=> Adding onPong and onPing resources of ws service

modules/web/js/ballerina/diagram2/views/default/components/utils/connector-properties.jsx, modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css, modules/web/js/ballerina/diagram2/views/default/components/utils/property-window.jsx
=> Add variable ref setting to connector props window

modules/web/js/ballerina/views/ballerina-file-editor.jsx
Fixes https://github.com/ballerinalang/composer/issues/4463
=> Validating imports when dropping function invocation statements from the tool palette

modules/web/js/ballerina/model/source-gen.js
=> Temp fix for endpoint ws.

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/tree.jsx
It does not make sense to delete them. They are mandatory.
=> Do not show delete button for the source and target

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx
=> fix setting new transform name when adding new parameters

modules/web/js/ballerina/diagram2/views/default/components/utils/properties-form.css
Fixes https://github.com/ballerinalang/composer/issues/4502
=> Setting the horizontal scroll bar is in front of the properties window

modules/web/js/ballerina/diagram2/views/default/sizing-util.js
Fixes https://github.com/ballerinalang/composer/issues/4490
=> Fixing overlapping params and tool menu in the panel decorator

modules/web/js/ballerina/diagram2/views/default/components/nodes/import-declaration-item.jsx
Fixes https://github.com/ballerinalang/composer/issues/4433
=> Allowing imports with aliases in design view

modules/web/js/ballerina/diagram2/views/compact/designer-defaults.js, modules/web/src/core/editor/dialogs/OpenedFileDeleteConfirmDialog.jsx, modules/web/src/core/workspace/dialogs/FileDeleteConfirmDialog.jsx
Fixes https://github.com/ballerinalang/composer/issues/4492
Fixes https://github.com/ballerinalang/composer/issues/4511
=> Increasing the space between statements so that action boxes can be accessed in the compact view + Changing the error messages when deleting files

modules/web/js/ballerina/model/tree/action-node.js, modules/web/js/ballerina/model/tree/function-node.js, modules/web/js/ballerina/model/tree/resource-node.js
Fixes https://github.com/ballerinalang/composer/issues/4514
Fixes https://github.com/ballerinalang/composer/issues/4064
=> Changing and incrementing the worker name of workers when adding multiple workers

modules/web/js/ballerina/diagram2/views/default/components/nodes/fork-join-node.jsx
Fixing the issue that have been caused by adding a semi colon in bc14869
=> Fixing #4497 - dropping semi-colon before parsing the fork source parts.

modules/web/js/ballerina/model/default-node-factory.js
Fixes https://github.com/ballerinalang/composer/issues/4517
=> Adding workers to fork-join by default

modules/web/js/ballerina/diagram2/views/default/positioning-util.js
Resolves #4515 
The Same issue inside the fork-join has been addressed with this PR.
=> Fix Issue #4515

modules/web/js/ballerina/model/tree/fork-join-node.js, modules/web/js/ballerina/tool-palette/tool-view.jsx
Fixes https://github.com/ballerinalang/composer/issues/3860
Fixes https://github.com/ballerinalang/composer/issues/4518
=> Making tooltips of connector actions readable and Fixing issue with join condition

modules/web/js/ballerina/diagram2/views/default/components/nodes/fork-join-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/4520
=> Fixing auto switching to source view when join condition is edited

modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.jsx
=> skip showing type name for anonymous structs in transformer

modules/web/js/ballerina/diagram2/views/default/components/nodes/top-level-nodes.jsx, modules/web/js/ballerina/model/tree-util.js, struct
Fixes https://github.com/ballerinalang/composer/issues/3514
=> Fixing issues when naming structs and adding package name with semi-colon

modules/web/js/ballerina/diagram2/views/default/components/nodes/import-declaration-item.jsx
Fixes https://github.com/ballerinalang/composer/issues/4079
=> Making the imports added editable

modules/web/js/ballerina/diagram2/views/default/components/nodes/global-item.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/globals-expanded.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/import-declaration-item.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/parameter-definition.jsx, modules/web/js/ballerina/tool-palette/item-provider/default-tools.js, modules/web/src/core/workspace/plugin.js
Fixes https://github.com/ballerinalang/composer/issues/3983
Fixes https://github.com/ballerinalang/composer/issues/3377
=> Fix issues of tool tips in the tool palette and program directory

modules/web/src/plugins/try-it/views/http-client.jsx, modules/web/src/plugins/try-it/views/http-client.scss
=> Modified try-it ui for new design.

modules/web/src/plugins/debugger/views/console-decorators/http-service-decorator.jsx
Fixes https://github.com/ballerinalang/composer/issues/4550
=> Made http service decorator to a react component.

modules/web/js/ballerina/diagram2/views/default/components/nodes/annotation-attachment-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/annotation-container.jsx, modules/web/js/ballerina/env/helpers/annotation-helper.js, modules/web/js/ballerina/model/source-gen.js, modules/web/js/ballerina/model/tree-builder.js, modules/web/source-gen/tree.g
Fixes https://github.com/ballerinalang/composer/issues/4453
Fixes https://github.com/ballerinalang/composer/issues/4295
Fixes https://github.com/ballerinalang/composer/issues/4461
=> Fixing issues with @doc annotations of the builtin package in the constructs

modules/web/js/ballerina/model/source-gen.js, modules/web/js/ballerina/model/tree-builder.js, modules/web/source-gen/defualt-ws.json, modules/web/source-gen/tree.g
Fixes https://github.com/ballerinalang/composer/issues/4555
Fixes https://github.com/ballerinalang/composer/issues/4557
=> Allowing imports with aliases in source view when given from the design view

modules/web/js/ballerina/diagram2/views/default/components/decorators/autosuggest-html.jsx, modules/web/js/ballerina/views/swagger-view.jsx, modules/web/src/plugins/debugger/LaunchManager/LaunchManager.js, modules/web/src/plugins/try-it/views/http-client.jsx, modules/web/src/plugins/try-it/views/http-client.scss, modules/web/src/plugins/try-it/views/try-it-container.jsx, modules/web/src/plugins/try-it/views/try-it-container.scss
Fixes https://github.com/ballerinalang/composer/issues/4091, https://github.com/ballerinalang/composer/issues/4459
=> Separated try-it clients base on their protocol.

modules/web/src/plugins/try-it/views/http-client.jsx, modules/web/src/plugins/try-it/views/http-client.scss, modules/web/src/plugins/try-it/views/try-it-container.jsx
=> Made content-type an editable dropdown in try-it.

modules/web/js/ballerina/swagger-parser/swagger-parser.js
Fixes https://github.com/ballerinalang/composer/issues/4540
=> Using JSON.stringfy instead of manually strigifying values in swagger parser.

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-definition-item.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/4566
Fixes https://github.com/ballerinalang/composer/issues/4140
=> Show error messages when adding invalid content to structs

modules/web/js/ballerina/diagram2/views/default/components/nodes/argument-parameter-definition-holder.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx, modules/web/src/core/workspace/dialogs/FileDeleteConfirmDialog.jsx, modules/web/src/core/workspace/plugin.js
Fixes https://github.com/ballerinalang/composer/issues/3435
Fixes https://github.com/ballerinalang/composer/issues/3612
Fixes https://github.com/ballerinalang/composer/issues/3586
=> Fix issues #3435, #3612 and #3586

issue_template.md
Add issue template into composer repo
=> Add issue template into composer repo

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/app/StartBrowser.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/app/WorkspaceServiceRunner.java
Works with : Linux, Windows, Mac
Fixes https://github.com/ballerinalang/composer/issues/2245
=> Navigate to composer browser window when the composer starts

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.css, modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.css, modules/web/js/ballerina/diagram2/views/default/components/transform/variable-endpoint.jsx
=> Format UI of editting temp variables and params in transform expanded

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx, modules/web/src/plugins/import-struct/dialogs/import-struct-dialog.jsx
fix #4269 
fix #4315 
fix #4265
=> fix Struct JSON import validations

modules/services/workspace-service/findbugs-exclude.xml, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/Command.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LaunchManager.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/LauncherConstants.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/TerminatorWindows.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/launcher/dto/CommandDTO.java, modules/web/src/plugins/debugger/LaunchManager/LaunchManager.js, modules/web/src/plugins/debugger/plugin.js, modules/web/src/plugins/debugger/views/LauncherConfigDialog.jsx
Resolves : https://github.com/ballerinalang/composer/issues/3963 and https://github.com/ballerinalang/composer/issues/4612
=> Fix issues and remove unused code in Launcher

modules/web/js/ballerina/diagram2/views/default/components/nodes/catch-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/3075
=> Fixing issue when editing the parameters of the catch statement

modules/web/js/ballerina/model/tree-builder.js
=> Fix the issue with go to source in join and timeout

modules/web/js/ballerina/tool-palette/tool-group-view.jsx, modules/web/js/ballerina/tool-palette/tool-view.jsx
=> Fix the issue with package documentation tab

modules/web/js/ballerina/diagram2/views/default/components/nodes/top-level-nodes.jsx
Fixes https://github.com/ballerinalang/composer/issues/2834
=> Removing 'Current Package' from import suggestions

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx, modules/web/src/plugins/import-struct/dialogs/import-struct-dialog.jsx
=> fix Struct generation for nested JSON samples

modules/web/js/ballerina/diagram2/views/default/components/decorators/panel-decorator.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/function.jsx, modules/web/js/ballerina/diagram2/views/default/components/transform/operator.jsx
Fixes https://github.com/ballerinalang/composer/issues/3627
Fixes https://github.com/ballerinalang/composer/issues/3047
=> Avoid having invalid names for constructs 

modules/web/js/ballerina/diagram2/views/default/components/decorators/action-box.jsx, modules/web/js/ballerina/diagram2/views/default/components/decorators/lifeline.jsx
Fixes https://github.com/ballerinalang/composer/issues/4658
=> Avoid deleting the default worker

modules/web/js/ballerina/diagram2/views/default/components/nodes/if-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/while-node.jsx
Fixes https://github.com/ballerinalang/composer/issues/4596
=> Fix issues when modifying the conditions of if and while statements

modules/web/js/ballerina/utils/ace-mode.js
Fixes https://github.com/ballerinalang/composer/issues/4679
=> Include lengthof and typeof as keywords

modules/web/js/ballerina/diagram2/views/default/components/nodes/fork-join-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/if-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/transaction-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/try-node.jsx, modules/web/js/ballerina/diagram2/views/default/components/nodes/while-node.jsx, modules/web/js/ballerina/model/source-gen.js, modules/web/source-gen/tree.g
Fixes https://github.com/ballerinalang/composer/issues/4593
Fixes https://github.com/ballerinalang/composer/issues/4681
=> Fix issues #4593 and #4681

modules/web/js/ballerina/diagram2/views/default/components/decorators/statement-decorator.jsx
Fixes https://github.com/ballerinalang/composer/issues/4675
=> Remove semicolon from statements in the design view

modules/web/js/ballerina/diagram2/views/default/components/nodes/global-item.jsx, modules/web/js/ballerina/diagram2/views/default/sizing-util.js
Fixes https://github.com/ballerinalang/composer/issues/4589
Fixes https://github.com/ballerinalang/composer/issues/4685
=>  Truncate global identifiers to fit the size of the global container

modules/web/js/ballerina/model/default-node-factory.js
Fixes https://github.com/ballerinalang/composer/issues/4695
=> Set default values when struct types are included as parameters in function invocations

modules/web/js/ballerina/diagram2/views/default/components/utils/connector-properties.jsx
Fixes https://github.com/ballerinalang/composer/issues/4698
=> Show configure properties of an endpoint when creation is done outside the endpoint inside a function

modules/web/js/ballerina/model/default-node-factory.js
Fixes https://github.com/ballerinalang/composer/issues/4716
=> Fix incorrect default config for ftp service

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapper.java, modules/services/workspace-service/src/test/resources/samples/service/expected.json
This PR is to align the composer with the changes introduced by https://github.com/ballerinalang/ballerina/pull/4143
=>  Align composer with the changes to identifier literals in AST

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapper.java, modules/services/workspace-service/src/test/resources/samples/service/expected.json
Reverts ballerinalang/composer#4709
Waiting for https://github.com/ballerinalang/ballerina/pull/4143 to be merged.
=> Revert " Align composer with the changes to identifier literals in AST"

modules/web/scss/modules/ballerina-editor.scss
=> Fix Issue #4711

modules/web/src/plugins/export-diagram/dialogs/export-diagram-dialog.jsx, modules/web/src/plugins/export-diagram/plugin.js
=> Fix the issue with export diagram file tree

modules/web/src/plugins/welcome-tab/views/samples-preview.jsx
=> Register onClick on the thumbnail itself instead of thumbnail container

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerResourceMapper.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapper.java, modules/web/.eslintignore, modules/web/js/ballerina/diagram/views/default/components/decorators/annotation-attribute-key.jsx, modules/web/js/ballerina/diagram/views/default/components/decorators/annotation-button-events.js, modules/web/js/ballerina/diagram/views/default/components/nodes/annotation-attachment-attribute-node.jsx, modules/web/js/ballerina/model/source-gen.js, modules/web/js/ballerina/model/tree/resource-node.js, modules/web/js/ballerina/model/tree/service-node.js, modules/web/js/ballerina/swagger-parser/swagger-parser.js, modules/web/source-gen/tree.g, modules/web/src/plugins/try-it/views/http-client.scss
Changes for https://github.com/ballerinalang/ballerina/pull/4143
=> Modified annotation attribute name to be an identifier.

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/completion/resolvers/AbstractItemResolver.java
=> Fix Issue #4418

modules/web/src/core/workspace/components/ExplorerItem.jsx, modules/web/src/core/workspace/constants.js, modules/web/src/core/workspace/model/file.js, modules/web/src/core/workspace/model/folder.js, modules/web/src/core/workspace/plugin.js, modules/web/src/core/workspace/views/WorkspaceExplorer.jsx
Previously we only handled opened folders via
the full path and we didn't have any model object
representing the opened folder in workspace. For
program dir related improvements for composer, we
need some attributes for folders opened in workspace.
=> Improve workspace folder handling with models

modules/web/src/plugins/ballerina/diagram/views/default/components/utils/server-connector-properties-form.jsx
Fixes https://github.com/ballerinalang/composer/issues/4751
=> Modify service property window to add annotation names as identifier nodes

modules/js-tests/package-lock.json, modules/js-tests/package.json, modules/js-tests/src/test/js/source-gen-test.js, modules/js-tests/src/test/resources/passing/exclusive/array-access-statment.bal, modules/web/source-gen/gen-source-gen.js, modules/web/source-gen/tree.g, modules/web/src/plugins/ballerina/model/source-gen.js, modules/web/src/plugins/ballerina/model/tree-builder.js
1. Updating indentifer with pipe syntax to ballerinalang/ballerina@f19f881
2. Add command to debug source gen tests.
3. Adding test file for #4670
4. Include all the tests in the build.
=> Improving source gen

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/composerapi/utils/RequestHandler.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/TreeVisitor.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/model/Function.java
With this PR, fix the doc annotation issues
=> Fix Doc annotations

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/util/positioning/resolver/BlockStatementScopeResolver.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFileRestService.java
Fix Compilation Failures due to https://github.com/ballerinalang/ballerina/pull/4228
=> Fix compilation failures

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/local/LocalFSWorkspace.java, modules/web/src/core/workspace/plugin.js, modules/web/src/plugins/ballerina/constants.js, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/top-level-nodes.jsx, modules/web/src/plugins/ballerina/dialogs/FixPackageNameOrPathConfirmDialog.jsx, modules/web/src/plugins/ballerina/plugin.js, modules/web/src/plugins/ballerina/utils/program-dir-utils.js, modules/web/src/plugins/ballerina/views/ballerina-file-editor.jsx
=> Ask file to be moved to correct dir or pkg declaration to be fixed upon entering invalid pkg name/path combinations

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/langserver/LangServerManager.java
=> Fix Issue #4783

modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/endpoint-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/worker-node.jsx
=> Fix the issue cannot rename endpoints and workers.

modules/web/src/plugins/ballerina/diagram/diagram.jsx
=> Fix the issue where action view doesn't render when error presented

modules/js-tests/src/test/resources/passing/type_of_test.bal, modules/web/source-gen/defualt-ws.json, modules/web/source-gen/tree.g, modules/web/src/plugins/ballerina/model/source-gen.js
=> Fix Issue #4793

modules/web/src/plugins/ballerina/model/default-node-factory.js
=> Fix Issue #4790

modules/web/src/core/workspace/dialogs/FileSaveDialog.jsx, modules/web/src/core/workspace/handlers.js
=> Fix the issue of the title of the save as dialog box.

modules/web/src/plugins/ballerina/utils/ace-mode.js
Added
* native
* datatable
* blob
* all
* some
* returns
Removed
* xmlDocument
* throws
* messege
=> Updated keywords for syntax highlighting

docs/plugins/readme.md, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/Workspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/cloud/CloudWorkspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/local/LocalFSWorkspace.java, modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/WorkspaceService.java, modules/web/src/core/editor/plugin.js, modules/web/src/core/view/tree-view/TreeNode.jsx, modules/web/src/core/workspace/fs-util.js, modules/web/src/core/workspace/plugin.js, modules/web/src/plugins/ballerina/plugin.js, modules/web/src/plugins/ballerina/utils/program-dir-utils.js
=> Add pkg declr automatically to files

modules/web/scss/modules/ballerina-editor.scss, modules/web/src/plugins/ballerina/configs/designer-defaults.js, modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/assignment-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/variable-def-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/designer-defaults.js, modules/web/src/plugins/ballerina/diagram/views/default/sizing-util.js, modules/web/src/plugins/ballerina/model/tree/invocation-node.js
This PR includes : 
- New action Invocation view design
=> New action invocation arrow UI

modules/web/scss/modules/ballerina-editor.scss, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/if-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/if-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/sizing-util.js
This PR includes : 
- New If node design
=> Flowchart if node design

modules/web/src/plugins/ballerina/tool-palette/tool-palette-view.jsx, modules/web/src/plugins/ballerina/tool-palette/tool-view.jsx
=> Fix Issue #4789

modules/js-tests/src/test/js/source-gen-test.js, modules/services/workspace-service/src/test/java/org/ballerinalang/composer/service/workspace/swagger/SwaggerServiceMapperTest.java, modules/services/workspace-service/src/test/resources/samples/transformer/transformer-expected.json
Please merge after https://github.com/ballerinalang/ballerina/pull/4282 is merged.
=> Allow comments everywhere

modules/web/src/plugins/ballerina/interactions/button.jsx, modules/web/src/plugins/ballerina/interactions/button.scss
Button is a HTML element and positioned absolute. Following props can be passed.
```
<Button
width={100}
height={50}
x={100}
y={200}
buttonX={30}
buttonY={20}
showAlways
/>
```
=> add new interaction button

modules/web/src/plugins/ballerina/interactions/button.jsx, modules/web/src/plugins/ballerina/interactions/button.scss
Menu is placed right hand side to the button
=> fix menu and add button placements

modules/web/scss/modules/ballerina-editor.scss, modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/client.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/if-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/if-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/resource-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/while-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/while-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/designer-defaults.js
This PR includes the following : 
- Improving flow control condition text styles
Before:
Now:
- Correct client name for each resource with text wrapping
Before:
Now:
- Showing full condition text on hover for while and if
- Fixing action box positioning
- ESLint fixes
=> Design view improvements

modules/web/src/plugins/ballerina/interactions/button.jsx, modules/web/src/plugins/ballerina/interactions/interaction.scss
You can add colors via `buttonColor` and `buttonIconColor` props as following sample config. Apart from that you can use `hideIconBackground` prop to circle background of button
```
<Button
bBox={{ x: 200, y: 100, h: 500, w: 500 }}
buttonX={0}
buttonY={0}
buttonColor={'red'}
buttonIconColor={'black'}
>
<Menu>
<Item
label='If'
icon='fw fw-dgm-if-else'
callback={(data) => { alert(data.name); }}
data={{ name: 'if condition' }}
/>
<Item
label='While'
icon='fw fw-dgm-while'
callback={(data) => { alert(data.name); }}
data={{ name: 'while condition' }}
/>
<Item
label='Send'
icon='fw fw-worker-invoke'
callback={(data) => { alert(data.name); }}
data={{ name: 'send stmt' }}
/>
<Item
label='Receive'
icon='fw fw-worker-reply'
callback={(data) => { alert(data.name); }}
data={{ name: 'receive stmt' }} …
```
=> add prop configs for button colors

modules/web/src/core/workspace/components/styles.scss, modules/web/src/plugins/debugger/views/DebuggerPanel.scss
=> left debugger panel styles

modules/web/src/plugins/ballerina/diagram/views/default/components/transform/transform-expanded.css, modules/web/src/plugins/ballerina/diagram/views/default/components/transform/transform-expanded.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/transform/transform-node-manager.js, modules/web/src/plugins/ballerina/diagram/views/default/components/transform/transform-render.js, modules/web/src/plugins/ballerina/interactions/interaction.scss, modules/web/src/plugins/ballerina/interactions/item.jsx, modules/web/src/plugins/ballerina/interactions/menu.jsx, modules/web/src/plugins/ballerina/interactions/transform-button.jsx
=> fix transform operator add menu support

modules/web/src/core/layout/commands.js, modules/web/src/plugins/ballerina/diagram/diagram.jsx, modules/web/src/plugins/ballerina/diagram/views/default/controller-positioning-util.jsx, modules/web/src/plugins/ballerina/interactions/button.jsx, modules/web/src/plugins/ballerina/views/source-editor.jsx, modules/web/src/plugins/debugger/constants.js, modules/web/src/plugins/debugger/menus.js, modules/web/src/plugins/debugger/plugin.js
=> Add mode switch btn to diagram & other fixes

modules/web/src/plugins/ballerina/diagram/views/default/components/transform/transform-expanded.css
=> adjust transform menu back button

modules/web/src/plugins/ballerina/interactions/interaction.scss, modules/web/src/plugins/ballerina/interactions/lifeline-button.jsx
This is to add the back button to the life line dropdown
=> Added back button to lifeline dropdown

modules/web/public/index.html, modules/web/src/core/app.js
Reverts ballerinalang/composer#4902
=> Revert "Fixes to greetings"

modules/web/src/core/editor/handlers.js, modules/web/src/plugins/ballerina/views/source-editor.jsx
Fixes the issue : https://github.com/ballerinalang/composer/issues/4907
=> Fix file editing in split view after jumping to source & tab change

modules/web/src/core/editor/views/EditorTabs.jsx, modules/web/src/plugins/ballerina/views/ballerina-file-editor.jsx, modules/web/src/plugins/ballerina/views/source-editor.jsx
Fix issues related to split-view editing and go-to-source while in split view
=> More fixes to source-editor revamp

modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/connector-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/worker-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/controller-positioning-util.jsx, modules/web/src/plugins/ballerina/model/tree/worker-node.js
=> Fixes for #4858 &  #4917

modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/while-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/designer-defaults.js, modules/web/src/plugins/ballerina/diagram/views/default/sizing-util.js
Add left margin to extend worker width and place while nodes when nested. Refer below screenshot.
=> Nested while constructs

modules/web/src/plugins/ballerina/diagram/views/default/components/transformer/transformer-node-mapper.js, modules/web/src/plugins/ballerina/diagram/views/default/controller-positioning-util.jsx, modules/web/src/plugins/ballerina/interactions/area.jsx, modules/web/src/plugins/ballerina/interactions/button.jsx, modules/web/src/plugins/ballerina/interactions/interaction.scss, modules/web/src/plugins/ballerina/interactions/lifeline-button.jsx, modules/web/src/plugins/ballerina/interactions/transform-button.jsx
- Remove button appear animation from always shown buttons
- Refactor transform code
- Separate button and button area into two components, this allows place multiple buttons in one area as following sample code
```html
<Area bBox={{ x: 200, y: 300, h: 500, w: 500 }}>
<Button
buttonX={40}
buttonY={50}
buttonRadius={10}
>
<Menu>
<Item
label='If'
icon='fw fw-dgm-if-else'
callback={(data) => { alert(data.name); }}
data={{ name: 'if condition' }}
/>
</Menu>
</Button>
<Button
buttonX={80}
buttonY={50}
buttonRadius={10}
>
<Menu>
<Item
label='While'
icon='fw fw-dgm-while'
callback={(data) => { alert(data.name); }}
data={{ name: 'while condition' }}
/>
</Menu>
</Button>
</Area>
```
=> Button improvements and code refactor

modules/web/src/plugins/ballerina/tool-palette/item-provider/worker-tools.js
=> [Fixed #4933]Update While icon in the plus menu

modules/web/src/plugins/ballerina/diagram/views/default/controller-positioning-util.jsx, modules/web/src/plugins/ballerina/interactions/lifeline-button.jsx
FIx page scroll to bottom when you add a worker or an endpoint.
=> Fix page scroll to bottom on worker add.

modules/web/scss/modules/ballerina-editor.scss, modules/web/src/plugins/ballerina/model/tree/worker-node.js, modules/web/src/plugins/ballerina/views/ballerina-file-editor.jsx, modules/web/src/plugins/ballerina/views/view-button.jsx
* Highlight currently selected view
* Fix tree getting invalid when deleting worker.
=> Highlight currently selected view

modules/web/scss/modules/ballerina-editor.scss, modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/client.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/action-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/function-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/if-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/resource-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/while-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/designer-defaults.js
This PR includes;
- New client line design
- Titles in while and if nodes
=> Improvements to client line and if,while

modules/web/src/plugins/ballerina/interactions/interaction.scss
The changes done to the menu 
Add connector changes
=> styling changes to interaction menu

modules/web/src/plugins/export-diagram/dialogs/export-diagram-dialog.jsx
Description.
This will fix the issue with jquery selector [1] to select diagram from the composer as it's has special characters in the ID attribute.
[1]. https://api.jquery.com/category/selectors/
=> Fix the issue with export diagram.

modules/web/webpack.config.js
This PR will resolve the composer theme build issue where the themes folder is being deleted upon the npm build.
=> Fix webpack theme build issue

modules/web/src/plugins/ballerina/diagram/views/default/components/utils/properties-form.css
=> Changing the look and feel of options pop up

modules/web/src/plugins/ballerina/model/tree-util.js, modules/web/src/plugins/ballerina/model/tree/action-node.js, modules/web/src/plugins/ballerina/model/tree/block-node.js, modules/web/src/plugins/ballerina/model/tree/connector-node.js, modules/web/src/plugins/ballerina/model/tree/function-node.js, modules/web/src/plugins/ballerina/model/tree/resource-node.js
=> improve worker and endpoint name generation

modules/web/src/plugins/ballerina/diagram/views/action/sizing-util.js, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/foreach-node.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/while-statement-decorator.jsx, modules/web/src/plugins/ballerina/diagram/views/default/positioning-util.js, modules/web/src/plugins/ballerina/diagram/views/default/sizing-util.js, modules/web/src/plugins/ballerina/model/abstract-tree-util.js, modules/web/src/plugins/ballerina/model/default-node-factory.js, modules/web/src/plugins/ballerina/utils/monarch-grammar.js
PR contains foreach rendering logic.
=> Foreach implementation

modules/web/src/plugins/ballerina/model/tree-util.js
Fixes https://github.com/ballerinalang/composer/issues/5014
=> Fix arrow not drawing for new client respond client invocation

modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/action-invocation-decorator.jsx
=> check view state invocation is undefined and assign default values

modules/web/src/plugins/ballerina/diagram/views/default/components/transformer/transformer-expanded.css, modules/web/src/plugins/ballerina/diagram/views/default/components/transformer/transformer-expanded.jsx, modules/web/src/plugins/ballerina/diagram/views/default/components/transformer/transformer-node-mapper.js, modules/web/src/plugins/ballerina/interactions/button.jsx, modules/web/src/plugins/ballerina/interactions/interaction.scss
- fix button and transformer z indexes to avoid conflicts
- remove isComment checks in transformer
=> fix transformer related issues
