modules/web/js/main.js
webpack.config.js

Adding ‘$’ behind alias names tells webpack to only match exact matches.
So requires like “ballerina/some/other/path” are not broken by this entry.
https://webpack.js.org/configuration/resolve/#resolve-alias
Also fixed a typo.

Use ballerina$ and workspace$ in webpack aliases

---

modules/web/js/tab/file-tab.js

Currently debug points are not updated along with content editing. Debug points indicated are incorrect after content editing. So to avoid confusion we are removing breakpoints alerting user with a message. 
We have to work on a better solution for this limitation along with https://github.com/ballerinalang/composer/issues/1075

remove breakpoints on content modified

---

modules/web/js/debugger/debug-manager.js
modules/web/js/debugger/tools.js

Even though we disabled action buttons from UI when debug session is over shortcut keys were still working. Introduced a common logic for button click and shortcut keypress.

refactored debug action buttons

---

modules/web/js/ballerina/utils/ace-formatter.js
modules/web/js/ballerina/utils/ace-mirror-worker.js
modules/web/js/ballerina/utils/ace-mode.js
modules/web/js/ballerina/utils/ace-worker.js
modules/web/js/ballerina/views/ballerina-file-editor.js
modules/web/js/ballerina/views/source-view.js
webpack.config.js

Using ‘ace-builds’ official package instead of ‘brace’
Added the syntax validation worker back.
The mirror worker for ace-editor is not provided in ace-builds. So had to manually add it. Filed an issue regarding this: ajaxorg/ace-builds#100

Using ace builds and adding syntax validating worker back

---

modules/web/js/ballerina/views/worker-invoke-view.js

When we add a worker invoke statement and without connecting it to the worker, try deleting. This would throw an error. With this fix, the particular issue has been fixed

Fixing worker invoke delete issue

---

modules/web/js/ballerina/views/reply-statement-view.js
modules/web/js/ballerina/views/worker-receive-view.js

This fixes the following issue,
Re positioning of the worker receiver after deleting an intermediate statement
Unnecessarily setting the activated target on worker receiver hover

Fixing minor positioning issues

---

modules/web/js/ballerina/utils/dropdown.js
modules/web/js/ballerina/views/connector-definition-view.js
modules/web/js/ballerina/views/constant-definition-view.js
modules/web/js/ballerina/views/constant-definitions-pane-view.js
modules/web/js/ballerina/views/function-definition-view.js
modules/web/js/ballerina/views/resource-parameter-view.js
modules/web/js/ballerina/views/resource-parameters-pane-view.js
modules/web/js/ballerina/views/return-type-view.js
modules/web/js/ballerina/views/return-types-pane-view.js
modules/web/js/ballerina/views/service-definition-view.js
modules/web/js/ballerina/views/struct-definition-view.js
modules/web/js/ballerina/views/struct-variable-definition-view.js
modules/web/js/ballerina/views/type-mapper-definition-view.js
modules/web/js/ballerina/views/variable-definitions-pane-view.js

This fix will listen to the keypress() event and then check whether pressed keys are Delete or Backspace. If it is not then proceed as before and if it is ignore these keys and let them do there default behaviors. This is only checked in Firefox as chrome and IE don't fire keypress() for Backspace or Delete.
Fix the issue: https://github.com/ballerinalang/composer/issues/1071
Note: Did not use the character code as Delete and "." has the same charcode

Fix the issue on Firefox where service/function/connector names doesn't change

---

modules/web/pom.xml

‘npm run clean’ which is run in the clean lifecycle depends on ‘rimraf’ node module. But when the project is just installed node modules are not installed yet. So need to install it pre-clean.

Install rimraf before clean lifecycle

---

modules/web/js/ballerina/utils/ace-mode.js
modules/web/js/ballerina/utils/ace-styles.css
modules/web/js/ballerina/views/source-view.js

'ace-builds' defines some features of the ace editor in separate modules. So need to require them explicitly if we want them.

Add search box to ace editor

---

modules/web/js/workspace/browser-storage.js

This was used as part of an storage API for backbone models, we are not
using them anymore. Keeping this code results in a never ending
string array of opened file IDs - being created in browser
storage. If we keep this, eventually users will exceed max allocated browser storage capacity.

Remove record array handling in browser storage API

---

modules/web/js/ballerina/utils/ace-formatter.js

A better fix for the current formatting issues is worked on at #1234

Avoid indenting closing '}' of an empty block

---

modules/web/css/sequence_diagram/sequenced-styles.css

fixes https://github.com/ballerinalang/composer/issues/553 , https://github.com/ballerinalang/composer/issues/300 and https://github.com/ballerinalang/composer/issues/133 
more info
http://stackoverflow.com/questions/15123953/svg-fill-url-behaving-strangely-in-firefox

fix svg icons not working on firefox 50.1

---

modules/web/js/ballerina/ast/connector-action.js
modules/web/js/ballerina/ast/connector-definition.js
modules/web/js/ballerina/ast/function-definition.js
modules/web/js/ballerina/ast/resource-definition.js
modules/web/js/ballerina/ast/service-definition.js
modules/web/js/ballerina/utils/common-utils.js

With this fix,
Remove the _new_ which had been added to the newly dragged and dropped elements and instead we use the Resource1, Service1, etc with incremented suffix

Fix Issue #1174

---

modules/web/js/ballerina/item-provider/initial-definitions.js
modules/web/js/ballerina/item-provider/tool-palette-item-provider.js
modules/web/js/ballerina/tool-palette/tool-view.js
modules/web/js/ballerina/tool-palette/tool.js
modules/web/webpack.config.js

Tool palette images are 'require'd with webpack so webpack optimizations also apply.

Create the img node for dragging at initialization and reuse to avoid duplication.

---

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java

Add function return node only when there are return types. This was to fix the tree comparison during statement validation

Source Validation fixes

---

modules/web/pom.xml

When building for electron mvn command should be passed '-Pelectron-build' to use the profile for electron build

Use build-electron as the build command for electron builds

---

modules/web/.storybook/webpack.config.js
modules/web/js/ballerina/components/image-util.jsx

path node module does not seem to work with webpack 1 for some reason. had to remove it from image utils for now.

Add the root directory to storybook webpack module fallbacks so requiring '/images/name.svg' works

---

modules/web/js/ballerina/ast/connector-action.js
modules/web/js/ballerina/components/panel-decorator.jsx
modules/web/js/ballerina/visitors/dimension-calculator/annotation-definition-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/dimension-calculator/connector-action-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/dimension-calculator/connector-definition-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/dimension-calculator/function-definition-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/dimension-calculator/resource-definition-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/dimension-calculator/service-definition-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/dimension-calculator/struct-definition-dimension-calculator-visitor.js
modules/web/js/ballerina/visitors/sizing-utils.js

Further, long names are truncated and renaming of main function stopped.

Renaming panel titles expands the input box accordingly

---

modules/web/js/ballerina/ast/resource-definition.js
modules/web/js/ballerina/components/editable-text.jsx

* Avoid calling forceUpdate inside the render method of Diagram by calling addChild silently
* Add a default value of empty string for EditableText children prop so input value prop is not set to undefined making it uncontrolled

Avoid warnings in the console

---

modules/web/css/sequence_diagram/sequenced-styles.css

Removing fill disables capturing mouse events in the svg element. On drag and drop a fill is dynamically added.

fix action box on hover

---

modules/web/js/ballerina/components/editable-text.jsx
modules/web/js/ballerina/components/panel-decorator.jsx
modules/web/js/ballerina/components/utils/tag-component.jsx

panel title is upadated on enter instead of every key press

Prevent values bleeding between EditableTexts of panel headers

---

modules/web/webpack.config.js

We use `constructor.name === 'SomeThing'` tests in our code to identify which class a certain object comes from. Such tests will fail when code is minified because function names are lost when mangling. This tells uglify plugin to avoid mangling function names.
React uses the presence of `process.env.NODE_ENV` set to `'production'` to remove warnings and stuff in production builds. So add that to define plugin.

Add minifying back to production build and avoid mangling function names

---

modules/web/js/ballerina/components/statement-container.jsx

Otherwise when a component is unmounted for example by deleting, those event handlers will still fire. This results in warining 'setState is called on an unmounted component'.

Unsubscribe from dragDrop and messageManager events when a StatementComponent unmounts

---

modules/web/js/ballerina/components/block-statement-decorator.jsx
modules/web/js/ballerina/components/transaction-statement.jsx
modules/web/js/ballerina/components/try-statement.jsx

If model prop is not passed ActionBox uses dropTarget as the model

Pass model prop to BlockStatementDecorator so ActionBox actions work for try catch and transaction statements

---

modules/web/js/ballerina/ast/expressions/key-value-expression.js
modules/web/js/ballerina/ast/expressions/reference-type-init-expression.js

When we are having a reference type init expression and if we edit it and focus out, an exception would be thrown. This is since when adding a child it by default fire the tree modified event. With the current implementation, we do need to trigger this event for inner types. We need to explicitly tell not to fire the events via the add child

Fix reference type init expression unnecessary tree modified event

---

modules/web/js/ballerina/components/global-definitions.jsx
modules/web/js/ballerina/components/globals-expanded.jsx
modules/web/js/ballerina/configs/designer-defaults.js
modules/web/js/ballerina/visitors/sizing-utils.js

* Put the variables pane height values into the designer defaults module
* Added doc comment for `getTextWidth` method from `sizing-utils`.

Minor code improvements

---

modules/web/js/ballerina/components/global-definitions.jsx
modules/web/js/ballerina/components/import-declaration.jsx
modules/web/js/ballerina/components/package-definition.jsx
modules/web/js/ballerina/visitors/dimension-calculator/package-definition-dimension-calculator-visitor.js

There were some numbers representing lengths of sub components of package definitions view that were hardcoded.
Defined them as constants. Also took the dimension constants to the dimension calc visitor so the parent viewfor package definition and imports know before hand the lenghts of sub components.

Define magic numbers as constants

---

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BallerinaComposerErrorStrategy.java
modules/web/js/ballerina/ast/connector-action.js
modules/web/js/ballerina/ast/connector-definition.js
modules/web/js/ballerina/ast/function-definition.js
modules/web/js/ballerina/ast/resource-definition.js
modules/web/js/ballerina/visitors/source-gen/connector-definition-visitor.js
modules/web/js/ballerina/visitors/source-gen/function-definition-visitor.js

While showing errors in source view, we already mark
the relevant line with error symbol in gutter, also we already receive
location info in a separate property for each error entry
in validate response. Having location info prep-ended
to error msg is not necessary as user already know
the location of the error by looking at source view
error decorations.

WS fixes and remove redundant location info in validate error msg

---

modules/web/js/debugger/debugger.css

Word wrap If console output is too long.

console - wrap if text line too long

---

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangFileRestService.java

Core's parser is not robust enough to keep on parsing when there is an error. If and when, the runtime supports reporting multiple errors instead breaking on first this fix can be removed.
@sameera-jayasoma please note.

Fixing #2101, Backend errors are ignored.

---

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BallerinaComposerErrorStrategy.java

EOF check is no longer needed since g4 now accepts empty file as a valid input. This check was preventing display of some errors such as extra quotation marks.

Make more parser errors visible in the editor.

---

modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelBuilder.java
modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangJSONModelConstants.java
modules/web/js/ballerina/ast/constant-definition.js

We cant visit the included variable def statement as a whole because that results in a recursive loop. (because variableDef is pointed to the parent constDef)
So visiting only the rhs. Identifier and the type are asigned to the json object seperately.
Fixes #2296

Global constant definitions rhs can be an expression

---

modules/web/js/ballerina/components/transform-render.js

There can be transform expanded views in more than one tabs. So $() matches everything on the document.
This is not what we want. We use this.container.find to only match stuff relevant to current mapper instance.

Use this.container.find instead of S()

---

modules/web/js/ballerina/ast/statements/variable-definition-statement.js
modules/web/js/ballerina/visitors/symbol-table/ballerina-ast-root-visitor.js

array type fields of structs not shown in transform https://github.com/ballerinalang/composer/issues/2228

array type fields of structs not shown in transform

---

modules/web/js/ballerina/components/global-definitions.jsx
modules/web/js/ballerina/components/global-item.jsx
modules/web/js/ballerina/components/globals-expanded.jsx
modules/web/js/ballerina/components/import-declaration-expanded.jsx
modules/web/js/ballerina/components/import-declaration-item.jsx
modules/web/js/ballerina/components/import-declaration.jsx
modules/web/js/ballerina/configs/designer-defaults.js
modules/web/js/ballerina/visitors/dimension-calculator/package-definition-dimension-calculator-visitor.js
modules/web/scss/modules/diagram.scss

The width of svg elements cannot be set by css by specification. It works in chrome but not in firefox.
Fixes #2397

Fix the imports and globals decorator for firefox

---

modules/web/js/ballerina/ast/expressions/basic-literal-expression.js

The root cause for which this code was needed
is fixed by a fix which is pushed to core. Now,
in verbose mode, while building the model, core
will not un-escapse string literals.
Core-PR https://github.com/ballerinalang/ballerina/pull/2959

Remove string literal re-escaping of WS chars

---

modules/web/js/ballerina/components/transform-render.js

We don't need this now since we reposition on componentDidUpdate

Remove repositioning on jsplumb connection

---

modules/web/js/ballerina/ast/default-ast-factory.js

This particular issue can only be reproduced for the functions in the current package, having return parameters. This Fix Resolves #2953

Fix Issue No: 2953

---

modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.css

So when left content is empty the middle content does not float to left.

Add a min-height to left/right content divs

---

modules/web/scss/modules/ballerina-editor.scss
modules/web/src/core/editor/views/EditorTabs.jsx
modules/web/src/core/layout/handlers.js

Fixes https://github.com/ballerinalang/composer/issues/3123 , https://github.com/ballerinalang/composer/issues/3118
Fixes the following scenario as well:
"while split view active, close all opened tabs, refresh, this will trigger welcome page to opened. Welcome page will fill only half the page
for custom tabs, we need to avoid setting width calculated from split view history data" @kaviththiranga

Fixed split view shown for custom editors.

---

modules/web/js/ballerina/diagram/views/default/components/transform/transform-render.js

Arrow head is the second child for collapsed connections because background path is not there.

Fixed reposition for collapsed connections

---

modules/web/js/ballerina/diagram/views/default/components/transform/transform-statement.css
modules/web/js/ballerina/diagram2/views/default/components/decorators/lifeline.jsx
modules/web/js/ballerina/diagram2/views/default/components/transform/transform-statement-decorator.jsx

Setting it from css only works on chrome. Firefox follows the spec so its not possible to set height and width of svg elements from css.

Set transform statement box icon size inline

---

modules/web/scss/modules/layout.scss
modules/web/src/core/editor/views/EditorTabs.jsx
modules/web/src/core/layout/components/App.jsx

Also disallow dragging split view in when its not active

Fixed editor area being larger than the document size

---

modules/web/js/ballerina/env/environment.js
modules/web/js/ballerina/model/tree-util.js
modules/web/js/langserver/lang-server-client-controller.js
modules/web/js/langserver/langserver-channel.js

The getNewTempVar function returns an array of vars even when langserver fails. (They are not unique names though)

Made lang server client call all pending callbacks on websocket close

---

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx
modules/web/js/ballerina/diagram2/views/default/components/transform/transform-statement.css
modules/web/js/ballerina/views/design-view.jsx
modules/web/scss/modules/ballerina-editor.scss

Seperate transform extended layout from scrolling container.
Refactor hardcoded offsets in styles (for tool pallete).
Forward width/height details to transform overly.

Fix regression issues in Transformer layout

---

modules/web/js/ballerina/tool-palette/item-provider/operator-tools.js

This creates a binary expression instead of a literal.
Fixes #3669

Use brackets around default expression for unary + and -

---

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx

We can see defined "Struct1" and "Person" in the drop down list.

Add defined Structs into type selection drop down

---

modules/web/js/ballerina/diagram2/views/default/components/nodes/connector-node.jsx
modules/web/js/ballerina/diagram2/views/default/components/nodes/service-node.jsx

Only globals were validated using empty string check.
Added them for connector and service variales too.
Fixing issue
https://github.com/ballerinalang/composer/issues/3875

Prevent adding empty rows when adding variables.

---

modules/web/js/ballerina/views/ballerina-file-editor.jsx
modules/web/src/core/editor/plugin.js
modules/web/src/core/editor/views/EditorTabs.jsx
modules/web/src/core/layout/commands.js
modules/web/src/core/layout/handlers.js
modules/web/src/plugins/ballerina/plugin.js

+ support clones
+ support custom title providers
Doc tabs will now open new tab per each package. Tab title reflects package name.

Fixes to custom tabs (improve doc tabs)

---

modules/web/package.json

React 15.6.2 is MIT license.
https://reactjs.org/blog/2017/09/26/react-v16.0.html

Updated react version to 15.6.2

---

modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-definition-item.jsx
modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-definition.css
modules/web/js/ballerina/diagram2/views/default/components/nodes/struct-node.jsx
modules/web/scss/modules/ballerina-editor.scss
modules/web/src/config.js
modules/web/src/plugins/import-struct/constants.js
modules/web/src/plugins/import-struct/dialogs/import-struct-dialog.jsx
modules/web/src/plugins/import-struct/plugin.js

This feature will add a button called "Import from JSON" in the Struct Definition view.
User can provide a sample JSON on pop up dialog box 
Upon importing Struct fields will be generated from the JSON

Struct generation by importing JSON

---

modules/web/src/core/utils/object-utils.js

Fixes : https://github.com/ballerinalang/composer/issues/4151
This issue was in arguments of a bound function throwing 'TypeError : 'arguments', 'callee', and 'caller' cannot be accessed in this context' during freezing. Fix is to avoid freezing functions.

Fix issue in loading composer in Safari

---

pom.xml

This dependency was not used by any sub modules. hence it should be safe to remove.

Removing connector dependency.

---

modules/web/js/ballerina/diagram2/views/default/components/transform/transform-node-manager.js

At the moment bound functions that are not in the builtin package are not rendered in the transform expanded view.
This fixes it for the drag-drop case. However rendering directly from the source is still broken.

Fix rendering bound functions that are not in the builtin package

---

modules/web/js/ballerina/diagram2/views/default/components/nodes/transformer-node.jsx
modules/web/js/ballerina/diagram2/views/default/components/transform/transform-expanded.jsx
modules/web/js/ballerina/tool-palette/tool-view.jsx
modules/web/js/ballerina/views/design-view.jsx

Now the reference to the active transform node is kept by storing its signature. (source, target, params and name) (eg: "<Person p, Employee e> Bar (int age)")
This means any change from the split view that changes the signature will take user back to the normal design view. This also happens for undo/redo changes. However changes from design view itself are handled.

Transform save active state

---

modules/web/js/ballerina/views/ballerina-file-editor.jsx

Switch to source view upon RUNTIME
errors from parser, only if, there
is no model available to render.

Gracefully handle runtime errors

---

modules/web/src/core/editor/plugin.js
modules/web/src/plugins/try-it/plugin.js

This fixes #4500
The issue occured because try-it and core plugins suplied different editors to be activated after closing try-it view.

Give the nextActive editor when closing a tab

---

modules/web/js/ballerina/views/source-editor.jsx

The issue was happening because [setContent](https://github.com/ballerinalang/composer/blob/3e5f90883b520aa8ffed50ef2746626471d9acd2/modules/web/js/ballerina/views/source-editor.jsx#L70) call in the undo manager triggers a rerender in source editor; and source editor [replaces](https://github.com/ballerinalang/composer/blob/master/modules/web/js/ballerina/views/source-editor.jsx#L297) the content again.
But this replacing does not trigger the execute method of undo manager, possibly because the content is the same. So the state we set to skip undo manager is never unset.

Fix undo redo / dirty state glitches

---

modules/web/src/plugins/debugger/views/Frames/frames.scss
modules/web/src/plugins/debugger/views/Frames/index.jsx

Styles for debugger frame name, fixes #4537

---

modules/web/src/plugins/ballerina/expression-editor/expression-editor-utils.js

Fix scroll going to the top when semicolon is hit in expression editor

---

modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.css
modules/web/js/ballerina/diagram/views/default/components/transform/transform-expanded.jsx
modules/web/js/ballerina/diagram/views/default/components/transform/transform-render.js
modules/web/js/ballerina/diagram/views/default/components/transform/transform-statement.css

Following fixes will add <> icon to connections. On mouse hover the converted type will be showing.
In future this menu will be improved to support select multiple conversions including reusing transformers.

Show conversion <> icon in the transformer connections

---

modules/web/src/plugins/ballerina/interactions/button.jsx
modules/web/src/plugins/ballerina/interactions/interaction.scss
modules/web/src/plugins/ballerina/interactions/item.jsx
modules/web/src/plugins/ballerina/interactions/menu.jsx

Following sample code piece could be used to render components
```
<Button
bBox={{ x: 100, y: 200, h: 50, w: 100 }}
buttonX={30}
buttonY={20}
showAlways
>
<Menu>
<Item
label='If'
icon='fw fw-dgm-if-else'
callback={(data) => { alert(data.name); }}
data={{ name: 'if condition' }}
/>
<Item
label='While'
icon='fw fw-dgm-while'
callback={(data) => { alert(data.name); }}
data={{ name: 'while condition' }}
/>
<Item
label='Send'
icon='fw fw-worker-invoke'
callback={(data) => { alert(data.name); }}
data={{ name: 'send stmt' }}
/>
<Item
label='Receive'
icon='fw fw-worker-reply'
callback={(data) => { alert(data.name); }}
data={{ name: 'receive stmt' }}
/>
</Menu>
</Button>
```
Rendered screenshot of above sample code

improve add menu with icon support and component restructure

---

modules/web/scss/modules/ballerina-editor.scss
modules/web/src/plugins/ballerina/diagram/diagram-util.js
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/action-invocation-decorator.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/client.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/lifeline.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/action-invocation-node.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/nodes/action-node.jsx
modules/web/src/plugins/ballerina/diagram/views/default/designer-defaults.js
modules/web/src/plugins/ballerina/diagram/views/default/positioning-util.js
modules/web/src/plugins/ballerina/diagram/views/default/sizing-util.js

This PR contains following improvements : 
- Hiding comments in design view
- Action node lifeline and client line rendering
- Client line design improvements
- Separating out action invocations from statement decorator
- Improve action invocation rendering
Before:
Now:

Design view improvements

---

modules/web/src/plugins/ballerina/interactions/button.jsx
modules/web/src/plugins/ballerina/interactions/interaction.scss

Button size can be configured via props. You can use `buttonRadius` property as following sample code piece
```
<Button
bBox={{ x: 100, y: 100, h: 500, w: 500 }}
buttonX={0}
buttonY={0}
buttonRadius={20}
showAlways
>
<Menu>
<Item
label='If'
icon='fw fw-dgm-if-else'
callback={(data) => { alert(data.name); }}
data={{ name: 'if condition' }}
/>
<Item
label='While'
icon='fw fw-dgm-while'
callback={(data) => { alert(data.name); }}
data={{ name: 'while condition' }}
/>
<Item
label='Send'
icon='fw fw-worker-invoke'
callback={(data) => { alert(data.name); }}
data={{ name: 'send stmt' }}
/>
<Item
label='Receive'
icon='fw fw-worker-reply'
callback={(data) => { alert(data.name); }}
data={{ name: 'receive stmt' }}
/>
</Menu>
</Button>
```
Screenshot of Rendered view of above code

make button size configurable via props

---

modules/web/scss/layout.scss
modules/web/scss/modules/header.scss
modules/web/scss/modules/menu.scss
modules/web/src/core/layout/components/App.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/action-box.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/panel-decorator.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/statement-decorator.css
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/statement-decorator.jsx
modules/web/src/plugins/ballerina/diagram/views/default/controller-positioning-util.jsx
modules/web/src/plugins/ballerina/model/tree/compilation-unit-node.js
modules/web/src/plugins/ballerina/plugin.js
modules/web/src/plugins/ballerina/views/source-editor.jsx

Fix positioning of top-level-nodes add btn
Remove debug action from action box
Remove annotation btn from panel header
Remove tool-palette
Remove tool-bar
Increate menu-bar height
Fix go-to-source for monaco
Disable stmt editing from design-view and enable go-to-source upon click

Fixes to design-view revamp

---

modules/web/scss/modules/ballerina-editor.scss
modules/web/src/plugins/ballerina/diagram/views/action/positioning-util.js
modules/web/src/plugins/ballerina/diagram/views/action/sizing-util.js
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/action-invocation-decorator.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/arrow-decorator.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/client-responder-decorator.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/client.jsx
modules/web/src/plugins/ballerina/diagram/views/default/components/decorators/lifeline.jsx
modules/web/src/plugins/ballerina/diagram/views/default/positioning-util.js
modules/web/src/plugins/ballerina/diagram/views/default/sizing-util.js
modules/web/src/plugins/ballerina/tool-palette/item-provider/worker-tools.js

This PR contains following fixes/improvements : 
- Add arrowhead to all workers to represent activation
- Change action invocation representation to show timeline on endpoint instead of worker
- Issue in sizing of action invocations in flow mode
Before : 
Now : 
- Change client responder arrows to have arrow head on client line
- Show client responder arrows in flow view
- Show transaction and try statements in lifeline +

Design view improvements/fixes

---

modules/web/scss/modules/ballerina-editor.scss
modules/web/src/core/editor/views/EditorTabs.jsx
modules/web/src/plugins/ballerina/diagram/diagram.jsx
modules/web/src/plugins/ballerina/model/default-node-factory.js
modules/web/src/plugins/ballerina/plugin.js
modules/web/src/plugins/ballerina/views/ballerina-file-editor.jsx
modules/web/src/plugins/ballerina/views/constants.js
modules/web/src/plugins/ballerina/views/design-view.jsx
modules/web/src/plugins/ballerina/views/source-view.jsx
modules/web/src/plugins/ballerina/views/view-button.jsx

This PR include the following changes. 
* Prevent options dialog popping out with node additions.
￼* Implement split view within ballerina file editor.
* Made the parser error display subtle. 
New Split View.

Moved split view inside the ballerina file editor tab.

---

modules/web/src/core/editor/constants.js
modules/web/src/plugins/ballerina/views/ballerina-file-editor.jsx

-  Fixes #4979
- Using a new Local storage key to tabs preview panel

Fix empty preview panel

---

modules/js-tests/pom.xml
modules/js-tests/src/test/js/source-gen-test.js
modules/server/server-launcher/src/main/java/org/ballerinalang/composer/server/launcher/ServerLauncher.java

Previously the back end composer services was started as a async maven
execution. The services may or may not be up when starting js tests.
By starting them inside the test script itself and waiting for services
stdout to print the success message, its guaranteed that the back end is
up when starting js tests.

Make sure back end is up before attempting js tests.

---

modules/server/server-launcher/src/main/java/org/ballerinalang/composer/server/launcher/ServerLauncher.java

These errors should not be visible unless user wants to see debug level logs.

Change log levels of config reading errors

---

modules/web/src/plugins/ballerina/views/ballerina-file-editor.jsx

This PR will fix the #4955 issue where the jump to source view on split view is not working as expected.

Fix issue #4955
